#!/usr/bin/env bash

set -euo pipefail

repo_root=$(CDPATH='' cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
bootstrap="$repo_root/scripts/bootstrap-global.sh"
real_sha256sum=$(command -v sha256sum)
test_root=$(mktemp -d "${TMPDIR:-/tmp}/bootstrap-global-tests.XXXXXX")
trap 'rm -rf -- "$test_root"' EXIT HUP INT TERM

managed_skills=(
    a11y
    agent-safety
    ansible
    powershell-pester-6
    powershell-module-engineering
    code-simplification
    dependabot
    git-commit
    github-actions-hardening
    msgraph
)

fail() {
    printf 'not ok - %s\n' "$*" >&2
    exit 1
}

assert_file_contains() {
    local path=$1
    local expected=$2

    grep -F "$expected" "$path" >/dev/null || fail "$path does not contain: $expected"
}

assert_same_file() {
    cmp -s "$1" "$2" || fail "files differ: $1 and $2"
}

assert_same_tree() {
    diff -qr "$1" "$2" >/dev/null || fail "directories differ: $1 and $2"
}

write_fake_tools() {
    local bin_dir=$1

    mkdir -p "$bin_dir"
    cat > "$bin_dir/apm" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf 'apm %s\n' "$*" >> "$HOME/.fake-command.log"
if [ -n "${FAKE_DOWNLOADED_EXECUTION_SENTINEL-}" ] && [ -f "${BASH_SOURCE[0]}.pinned" ]; then
    printf 'executed\n' >> "$FAKE_DOWNLOADED_EXECUTION_SENTINEL"
fi

if [ "${1-}" = install ]; then
    [ "${FAKE_APM_FAIL_STAGE-}" != install ] || exit 41
    for skill in code-simplification dependabot git-commit github-actions-hardening msgraph; do
        mkdir -p "$HOME/.agents/skills/$skill"
        printf 'installed %s\n' "$skill" > "$HOME/.agents/skills/$skill/SKILL.md"
    done
    mkdir -p "$HOME/.apm/apm_modules/fake"
    printf 'installed\n' > "$HOME/.apm/apm_modules/fake/state"
    printf '{"installed":true}\n' > "$HOME/.apm/config.json"
    mkdir -p "$HOME/.codex" "$HOME/.copilot"
    exit 0
fi

if [ "${1-}" = compile ]; then
    target=''
    output=''
    dry_run=false
    shift
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --target)
                target=$2
                shift 2
                ;;
            --output)
                output=$2
                shift 2
                ;;
            --dry-run)
                dry_run=true
                shift
                ;;
            *)
                shift
                ;;
        esac
    done
    stage="compile-write-$target"
    [ "$dry_run" = false ] || stage="compile-dry-$target"
    [ "${FAKE_APM_FAIL_STAGE-}" != "$stage" ] || exit 42
    if [ "$dry_run" = false ]; then
        mkdir -p "$(dirname "$output")"
        printf '# AGENTS.md\n<!-- Generated by APM CLI from .apm/ primitives -->\n%s\n' "$target" > "$output"
    fi
    exit 0
fi

if [ "${1-}" = --version ]; then
    fake_version=${FAKE_APM_VERSION:-0.28.0}
    if [ -f "${BASH_SOURCE[0]}.pinned" ]; then
        fake_version=$(cat "${BASH_SOURCE[0]}.pinned")
    fi
    printf 'APM %s\n' "$fake_version"
    exit 0
fi

exit 43
EOF

    cat > "$bin_dir/uname" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "${1-}" in
    -s) printf 'Linux\n' ;;
    -m) printf '%s\n' "${FAKE_UNAME_MACHINE:-x86_64}" ;;
    *) exit 90 ;;
esac
EOF

    cat > "$bin_dir/sha256sum" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
self_dir=$(CDPATH='' cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
if [ "$#" -eq 1 ]; then
    resolved=$(readlink -f -- "$1")
    if [ -n "${FAKE_SHA256_LOG-}" ]; then
        printf '%s\n' "$resolved" >> "$FAKE_SHA256_LOG"
    fi
    case "$resolved" in
        */install.sh)
            if [ "${FAKE_SHA256_MODE-}" != installer-mismatch ]; then
                printf '%s  %s\n' "${FAKE_PINNED_INSTALLER_HASH:?}" "$1"
                exit 0
            fi
            ;;
        */apm-linux-*.tar.gz)
            if [ "${FAKE_SHA256_MODE-}" != archive-mismatch ]; then
                printf '%s  %s\n' "${FAKE_PINNED_ARCHIVE_HASH:?}" "$1"
                exit 0
            fi
            ;;
        */archive-check/apm-linux-*/apm)
            if [ "${FAKE_SHA256_MODE-}" != member-mismatch ]; then
                printf '%s  %s\n' "${FAKE_PINNED_APM_HASH:?}" "$1"
                exit 0
            fi
            ;;
        "$self_dir/apm")
            if [ "${FAKE_SHA256_MODE-}" != existing-mismatch ] &&
                { [ "${FAKE_SHA256_MODE-}" != postinstall-mismatch ] || [ ! -f "$self_dir/apm.pinned" ]; }; then
                printf '%s  %s\n' "${FAKE_PINNED_APM_HASH:?}" "$1"
                exit 0
            fi
            ;;
        "${FAKE_INSTALL_TARGET-}/apm")
            if [ "${FAKE_SHA256_MODE-}" != postinstall-mismatch ]; then
                printf '%s  %s\n' "${FAKE_PINNED_APM_HASH:?}" "$1"
                exit 0
            fi
            ;;
    esac
fi
exec "${REAL_SHA256SUM:?}" "$@"
EOF
    chmod +x "$bin_dir/apm" "$bin_dir/sha256sum" "$bin_dir/uname"
}

new_case() {
    case_name=$1
    unset APM_INSTALL_DIR FAKE_ARCHIVE_FIXTURE FAKE_DOWNLOADED_EXECUTION_SENTINEL \
        FAKE_INSTALLER_EXECUTION_SENTINEL FAKE_INSTALLER_FIXTURE FAKE_INSTALL_TARGET \
        FAKE_PLATFORM_ARCH FAKE_SHA256_LOG FAKE_SHA256_MODE FAKE_UNAME_MACHINE || true
    case_root="$test_root/$case_name"
    case_home="$case_root/home"
    case_bin="$case_root/bin"
    mkdir -p "$case_home" "$case_bin"
    write_fake_tools "$case_bin"
}

run_bootstrap() {
    run_bootstrap_script "$bootstrap" "$@"
}

run_bootstrap_script() {
    local bootstrap_path=$1
    local platform_arch=x86_64 pinned_installer_hash pinned_archive_hash pinned_executable_hash
    shift
    case "${FAKE_UNAME_MACHINE:-x86_64}" in
        arm64|aarch64) platform_arch=arm64 ;;
    esac
    pinned_installer_hash=$(awk '$2 == "install.sh" { print $1 }' "$repo_root/.apm-checksums")
    pinned_archive_hash=$(awk -v name="apm-linux-$platform_arch.tar.gz" \
        '$2 == name { print $1 }' "$repo_root/.apm-checksums")
    pinned_executable_hash=$(awk -v name="apm-linux-$platform_arch/apm" \
        '$2 == name { print $1 }' "$repo_root/.apm-checksums")
    HOME="$case_home" PATH="$case_bin:/usr/bin:/bin" REAL_SHA256SUM="$real_sha256sum" \
        FAKE_PINNED_INSTALLER_HASH="$pinned_installer_hash" \
        FAKE_PINNED_ARCHIVE_HASH="$pinned_archive_hash" \
        FAKE_PINNED_APM_HASH="$pinned_executable_hash" "$bootstrap_path" "$@"
}

prepare_secure_download_fixtures() {
    local platform_arch=${1:-x86_64}
    fixture_root="$case_root/download-fixtures"
    fixture_bundle="$fixture_root/apm-linux-$platform_arch"
    mkdir -p "$fixture_bundle"
    cp "$case_bin/apm" "$fixture_bundle/apm"
    chmod +x "$fixture_bundle/apm"
    fixture_archive="$fixture_root/apm-linux-$platform_arch.tar.gz"
    tar -czf "$fixture_archive" -C "$fixture_root" "apm-linux-$platform_arch"
    fixture_installer="$fixture_root/install.sh"
    cat > "$fixture_installer" <<'EOF'
#!/usr/bin/env sh
set -eu
[ "${APM_NO_DIRECT_FALLBACK-}" = 1 ] || exit 81
case "${APM_RELEASE_BASE_URL-}" in file://*) ;; *) exit 82 ;; esac
[ -n "${VERSION-}" ] || exit 83
printf 'installer-executed\n' >> "${FAKE_INSTALLER_EXECUTION_SENTINEL:?}"
mirror=${APM_RELEASE_BASE_URL#file://}
temporary=${TMPDIR:-/tmp}/fake-apm-installer-$$
mkdir -p "$temporary"
archive_root="apm-linux-${FAKE_PLATFORM_ARCH:-x86_64}"
tar -xzf "$mirror/$VERSION/$archive_root.tar.gz" -C "$temporary"
mkdir -p "${APM_INSTALL_DIR:?}"
cp "$temporary/$archive_root/apm" "$APM_INSTALL_DIR/apm"
chmod +x "$APM_INSTALL_DIR/apm"
printf '%s\n' "${VERSION#v}" > "$APM_INSTALL_DIR/apm.pinned"
"$APM_INSTALL_DIR/apm" --version >/dev/null
rm -rf "$temporary"
EOF
    chmod +x "$fixture_installer"
    cat > "$case_bin/curl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
output=''
url=''
while [ "$#" -gt 0 ]; do
    case "$1" in
        --output) output=$2; shift 2 ;;
        http*) url=$1; shift ;;
        *) shift ;;
    esac
done
case "$url" in
    */install.sh) cp "${FAKE_INSTALLER_FIXTURE:?}" "$output" ;;
    */apm-linux-*.tar.gz) cp "${FAKE_ARCHIVE_FIXTURE:?}" "$output" ;;
    *) exit 84 ;;
esac
EOF
    chmod +x "$case_bin/curl"
    export FAKE_INSTALLER_FIXTURE="$fixture_installer"
    export FAKE_ARCHIVE_FIXTURE="$fixture_archive"
    export FAKE_PLATFORM_ARCH="$platform_arch"
    export FAKE_INSTALLER_EXECUTION_SENTINEL="$case_root/installer-executed"
    export FAKE_DOWNLOADED_EXECUTION_SENTINEL="$case_root/downloaded-executed"
    export APM_INSTALL_DIR="$case_bin"
    export FAKE_INSTALL_TARGET="$APM_INSTALL_DIR"
}

seed_old_state() {
    mkdir -p \
        "$case_home/.apm/.apm/skills/old" \
        "$case_home/.apm/apm_modules/old" \
        "$case_home/.codex" \
        "$case_home/.copilot" \
        "$case_home/.agents/skills"
    printf 'old manifest\n' > "$case_home/.apm/apm.yml"
    printf 'old lock\n' > "$case_home/.apm/apm.lock.yaml"
    printf 'old source\n' > "$case_home/.apm/.apm/skills/old/value"
    printf 'old module\n' > "$case_home/.apm/apm_modules/old/value"
    printf 'old config\n' > "$case_home/.apm/config.json"
    printf '# old codex\n' > "$case_home/.codex/AGENTS.md"
    printf 'project_doc_max_bytes = 77777\n\n' > "$case_home/.codex/config.toml"
    printf 'untouched copilot agents\n' > "$case_home/.copilot/AGENTS.md"
    for skill in "${managed_skills[@]}"; do
        [ "$skill" != msgraph ] || continue
        mkdir -p "$case_home/.agents/skills/$skill"
        printf 'old %s\n' "$skill" > "$case_home/.agents/skills/$skill/value"
    done
}

save_seed_state() {
    expected_root="$case_root/expected"
    mkdir -p "$expected_root"
    for relative_path in \
        .apm/apm.yml .apm/apm.lock.yaml .apm/.apm .apm/apm_modules .apm/config.json \
        .codex/AGENTS.md .codex/config.toml .copilot/copilot-instructions.md \
        .copilot/AGENTS.md; do
        if [ -e "$case_home/$relative_path" ]; then
            mkdir -p "$expected_root/$(dirname "$relative_path")"
            cp -a "$case_home/$relative_path" "$expected_root/$relative_path"
        else
            mkdir -p "$expected_root/absent/$(dirname "$relative_path")"
            : > "$expected_root/absent/$relative_path"
        fi
    done
    for skill in "${managed_skills[@]}"; do
        relative_path=".agents/skills/$skill"
        if [ -e "$case_home/$relative_path" ]; then
            mkdir -p "$expected_root/.agents/skills"
            cp -a "$case_home/$relative_path" "$expected_root/$relative_path"
        else
            mkdir -p "$expected_root/absent/.agents/skills"
            : > "$expected_root/absent/$relative_path"
        fi
    done
}

assert_seed_state_restored() {
    local relative_path

    for relative_path in \
        .apm/apm.yml .apm/apm.lock.yaml .apm/.apm .apm/apm_modules .apm/config.json \
        .codex/AGENTS.md .codex/config.toml .copilot/copilot-instructions.md \
        .copilot/AGENTS.md; do
        if [ -e "$expected_root/absent/$relative_path" ]; then
            [ ! -e "$case_home/$relative_path" ] || fail "rollback did not remove $relative_path"
        elif [ -d "$expected_root/$relative_path" ]; then
            assert_same_tree "$expected_root/$relative_path" "$case_home/$relative_path"
        else
            assert_same_file "$expected_root/$relative_path" "$case_home/$relative_path"
        fi
    done
    for skill in "${managed_skills[@]}"; do
        relative_path=".agents/skills/$skill"
        if [ -e "$expected_root/absent/$relative_path" ]; then
            [ ! -e "$case_home/$relative_path" ] || fail "rollback did not remove $relative_path"
        else
            assert_same_tree "$expected_root/$relative_path" "$case_home/$relative_path"
        fi
    done
}

new_case fresh
mkdir -p "$case_home/.codex" "$case_home/.copilot" "$case_home/private"
printf 'project_doc_max_bytes = 90001\n\n[features]\nexample = true\n' > "$case_home/.codex/config.toml"
printf 'do not touch\n' > "$case_home/.copilot/AGENTS.md"
printf 'private\n' > "$case_home/private/keep.txt"
cp "$case_home/.codex/config.toml" "$case_root/original-codex-config.toml"
cp "$case_home/.copilot/AGENTS.md" "$case_root/original-copilot-agents.md"
[ ! -e "$case_bin/codex" ] || fail 'fresh fixture unexpectedly provides Codex tooling'
fresh_output=$(run_bootstrap)
assert_file_contains "$case_home/.codex/AGENTS.md" '<!-- Generated by APM CLI from .apm/ primitives -->'
assert_file_contains "$case_home/.copilot/copilot-instructions.md" '<!-- Generated by APM CLI from .apm/ primitives -->'
assert_same_file "$case_root/original-codex-config.toml" "$case_home/.codex/config.toml"
assert_same_file "$repo_root/apm.yml" "$case_home/.apm/apm.yml"
assert_same_tree "$repo_root/.apm" "$case_home/.apm/.apm"
for skill in "${managed_skills[@]}"; do
    [ -d "$case_home/.agents/skills/$skill" ] || fail "fresh install omitted $skill"
done
assert_same_file "$case_root/original-copilot-agents.md" "$case_home/.copilot/AGENTS.md"
assert_file_contains "$case_home/private/keep.txt" 'private'
backup_dir=$(printf '%s\n' "$fresh_output" | sed -n 's/^Rollback snapshot retained at: //p')
[ -d "$backup_dir" ] || fail 'fresh install did not retain a snapshot'
[ "$(wc -l < "$backup_dir/inventory.tsv")" -eq 17 ] || fail 'snapshot inventory is incomplete'
assert_file_contains "$backup_dir/originally-absent.txt" '.agents/skills/msgraph'
printf 'ok - fresh install without Codex tooling, fidelity, 17-path inventory, and unmanaged files\n'

run_bootstrap >/dev/null
[ "$(find "$case_home/.apm/backups/agent-engineering-baseline" -mindepth 1 -maxdepth 1 -type d | wc -l)" -eq 2 ] ||
    fail 'idempotent rerun did not retain a second snapshot'
assert_same_file "$case_root/original-codex-config.toml" "$case_home/.codex/config.toml"
assert_same_file "$case_root/original-copilot-agents.md" "$case_home/.copilot/AGENTS.md"
! grep -E '^codex ' "$case_home/.fake-command.log" >/dev/null ||
    fail 'bootstrap invoked Codex tooling'
printf 'ok - idempotent rerun preserves user configuration byte-for-byte\n'

new_case dry_run
if ! run_bootstrap --dry-run > "$case_root/out" 2> "$case_root/err"; then
    cat "$case_root/err" >&2
    fail 'Bash dry run failed'
fi
assert_file_contains "$case_root/out" 'no user-profile files were changed'
[ ! -e "$case_home/.apm" ] || fail 'dry run created global APM state'
! grep -F 'apm install' "$case_home/.fake-command.log" >/dev/null || fail 'dry run invoked APM install'
printf 'ok - Bash dry run\n'

new_case unverified-existing-cli
export FAKE_SHA256_MODE=existing-mismatch
if run_bootstrap --dry-run > "$case_root/out" 2> "$case_root/err"; then
    fail 'unverified existing APM CLI was accepted'
fi
unset FAKE_SHA256_MODE
assert_file_contains "$case_root/err" 'does not match the pinned SHA256 checksum'
if [ -f "$case_home/.fake-command.log" ]; then
    ! grep -F 'apm --version' "$case_home/.fake-command.log" >/dev/null ||
        fail 'unverified existing APM CLI executed before checksum rejection'
fi
[ ! -d "$case_home/.apm/backups" ] || fail 'unverified CLI rejection mutated the profile'
printf 'ok - unverified existing CLI rejection before execution or mutation\n'

new_case verified-version-mismatch
export FAKE_APM_VERSION=999.999.999
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'verified APM CLI with an unexpected version was accepted'
fi
unset FAKE_APM_VERSION
assert_file_contains "$case_root/err" 'matches the reviewed digest but reports version 999.999.999'
[ ! -d "$case_home/.apm/backups" ] || fail 'version mismatch rejection mutated the profile'
printf 'ok - verified CLI version mismatch rejection before mutation\n'

new_case download-failure
rm "$case_bin/apm"
cat > "$case_bin/curl" <<'EOF'
#!/usr/bin/env bash
exit 55
EOF
chmod +x "$case_bin/curl"
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'installer download failure was ignored'
fi
[ ! -d "$case_home/.apm/backups" ] || fail 'download failure mutated the profile'
printf 'ok - installer download failure before mutation\n'

new_case tampered-installer
rm "$case_bin/apm"
export FAKE_SHA256_MODE=installer-mismatch
cat > "$case_bin/curl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
while [ "$#" -gt 0 ]; do
    if [ "$1" = --output ]; then
        printf 'tampered installer\n' > "$2"
        exit 0
    fi
    shift
done
exit 56
EOF
chmod +x "$case_bin/curl"
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'tampered installer was accepted'
fi
unset FAKE_SHA256_MODE
assert_file_contains "$case_root/err" 'does not match the pinned SHA256 checksum'
[ ! -d "$case_home/.apm/backups" ] || fail 'tampered installer mutated the profile'
printf 'ok - tampered installer rejection before mutation\n'

new_case missing-checksum-entry
prepare_secure_download_fixtures
rm "$case_bin/apm"
case_repository="$case_root/repository"
mkdir -p "$case_repository/scripts"
cp "$bootstrap" "$case_repository/scripts/bootstrap-global.sh"
cp "$repo_root/apm.yml" "$repo_root/apm.lock.yaml" "$repo_root/.apm-version" "$case_repository/"
cp -R "$repo_root/.apm" "$case_repository/.apm"
awk '$2 != "install.sh"' "$repo_root/.apm-checksums" > "$case_repository/.apm-checksums"
if run_bootstrap_script "$case_repository/scripts/bootstrap-global.sh" \
    > "$case_root/out" 2> "$case_root/err"; then
    fail 'missing checksum entry was accepted'
fi
assert_file_contains "$case_root/err" 'Expected exactly one pinned checksum for install.sh'
[ ! -e "$case_root/installer-executed" ] || fail 'installer ran without a pinned checksum'
[ ! -e "$case_root/downloaded-executed" ] || fail 'downloaded executable ran without a pinned checksum'
[ ! -d "$case_home/.apm/backups" ] || fail 'missing checksum entry changed profile state'
printf 'ok - missing checksum entry rejection before execution or profile mutation\n'

new_case secure-cli-install
prepare_secure_download_fixtures
rm "$case_bin/apm"
if ! run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    cat "$case_root/err" >&2
    fail 'verified local-mirror installation failed'
fi
[ -f "$case_root/installer-executed" ] || fail 'verified installer did not execute'
[ -f "$case_root/downloaded-executed" ] || fail 'verified executable did not execute'
assert_file_contains "$case_home/.fake-command.log" 'apm install --global --frozen'
assert_file_contains "$case_root/out" 'Global APM configuration is ready.'
printf 'ok - verified fresh CLI promotion through the private local mirror\n'

new_case arm64-secure-cli-install
export FAKE_UNAME_MACHINE=aarch64 FAKE_SHA256_LOG="$case_root/sha256.log"
prepare_secure_download_fixtures arm64
rm "$case_bin/apm"
if ! run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    cat "$case_root/err" >&2
    fail 'verified arm64 local-mirror installation failed'
fi
assert_file_contains "$case_root/sha256.log" 'apm-linux-arm64.tar.gz'
assert_file_contains "$case_root/sha256.log" 'archive-check/apm-linux-arm64/apm'
[ -f "$case_root/installer-executed" ] || fail 'verified arm64 installer did not execute'
[ -f "$case_root/downloaded-executed" ] || fail 'verified arm64 executable did not execute'
printf 'ok - arm64 CLI archive and member selection through the private local mirror\n'

new_case installer-checksum-failure
prepare_secure_download_fixtures
rm "$case_bin/apm"
export FAKE_SHA256_MODE=installer-mismatch
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'installer checksum failure was accepted'
fi
unset FAKE_SHA256_MODE
[ ! -e "$case_root/installer-executed" ] || fail 'bad installer executed'
[ ! -e "$case_root/downloaded-executed" ] || fail 'downloaded executable ran after installer failure'
[ ! -d "$case_home/.apm/backups" ] || fail 'installer checksum failure changed profile state'
printf 'ok - installer checksum failure before downloaded execution or profile mutation\n'

new_case archive-checksum-failure
prepare_secure_download_fixtures
rm "$case_bin/apm"
export FAKE_SHA256_MODE=archive-mismatch
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'archive checksum failure was accepted'
fi
unset FAKE_SHA256_MODE
[ ! -e "$case_root/installer-executed" ] || fail 'installer ran after archive checksum failure'
[ ! -e "$case_root/downloaded-executed" ] || fail 'downloaded executable ran after archive checksum failure'
[ ! -d "$case_home/.apm/backups" ] || fail 'archive checksum failure changed profile state'
printf 'ok - archive checksum failure before downloaded execution or profile mutation\n'

new_case archive-layout-failure
prepare_secure_download_fixtures
rm "$case_bin/apm"
mkdir -p "$case_root/bad-layout"
printf 'bad layout\n' > "$case_root/bad-layout/apm"
tar -czf "$FAKE_ARCHIVE_FIXTURE" -C "$case_root" bad-layout
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'unsafe archive layout was accepted'
fi
[ ! -e "$case_root/installer-executed" ] || fail 'installer ran after archive layout failure'
[ ! -e "$case_root/downloaded-executed" ] || fail 'downloaded executable ran after layout failure'
[ ! -d "$case_home/.apm/backups" ] || fail 'archive layout failure changed profile state'
printf 'ok - archive layout failure before downloaded execution or profile mutation\n'

new_case executable-checksum-failure
prepare_secure_download_fixtures
rm "$case_bin/apm"
export FAKE_SHA256_MODE=member-mismatch
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'executable member checksum failure was accepted'
fi
unset FAKE_SHA256_MODE
[ ! -e "$case_root/installer-executed" ] || fail 'installer ran after executable checksum failure'
[ ! -e "$case_root/downloaded-executed" ] || fail 'downloaded executable ran after member checksum failure'
[ ! -d "$case_home/.apm/backups" ] || fail 'member checksum failure changed profile state'
printf 'ok - executable member checksum failure before execution or profile mutation\n'

new_case postinstall-executable-checksum-failure
prepare_secure_download_fixtures
rm "$case_bin/apm"
export FAKE_SHA256_MODE=postinstall-mismatch
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'post-install executable checksum failure was accepted'
fi
unset FAKE_SHA256_MODE
[ -f "$case_root/installer-executed" ] || fail 'verified installer did not execute'
[ "$(wc -l < "$case_root/downloaded-executed")" -eq 1 ] ||
    fail 'wrapper invoked the promoted executable after its checksum changed'
[ ! -d "$case_home/.apm/backups" ] || fail 'post-install checksum failure changed profile state'
printf 'ok - promoted executable rehash before wrapper invocation or profile mutation\n'

new_case symlink
mkdir -p "$case_home/.codex"
printf 'outside\n' > "$case_root/outside"
ln -s "$case_root/outside" "$case_home/.codex/AGENTS.md"
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'symbolic-link target was accepted'
fi
assert_file_contains "$case_root/err" 'symbolic-link target'
assert_file_contains "$case_root/outside" 'outside'
[ ! -d "$case_home/.apm/backups" ] || fail 'symlink rejection mutated the profile'
printf 'ok - symbolic-link rejection\n'

new_case backup-namespace-symlink
mkdir -p "$case_home/.apm/backups" "$case_root/outside"
printf 'outside\n' > "$case_root/outside/sentinel"
ln -s "$case_root/outside" "$case_home/.apm/backups/agent-engineering-baseline"
if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
    fail 'symbolic-link backup namespace was accepted'
fi
assert_file_contains "$case_root/err" 'symbolic-link target'
assert_file_contains "$case_root/outside/sentinel" 'outside'
[ "$(find "$case_root/outside" -mindepth 1 -maxdepth 1 | wc -l)" -eq 1 ] ||
    fail 'backup namespace rejection wrote outside the profile boundary'
printf 'ok - symbolic-link backup namespace rejection\n'

for failure_stage in install compile-dry-codex compile-dry-copilot compile-write-codex compile-write-copilot; do
    new_case "rollback-$failure_stage"
    seed_old_state
    save_seed_state
    export FAKE_APM_FAIL_STAGE=$failure_stage
    if run_bootstrap > "$case_root/out" 2> "$case_root/err"; then
        fail "native-stage failure was ignored: $failure_stage"
    fi
    unset FAKE_APM_FAIL_STAGE || true
    assert_file_contains "$case_root/err" 'Rollback completed successfully'
    assert_seed_state_restored
done
printf 'ok - complete rollback at every native-command stage\n'

printf 'All Bash bootstrap behavior tests passed.\n'
