BeforeAll {
    . "$PSScriptRoot/../scripts/Bootstrap-Global.ps1"
}

Describe 'Bootstrap-Global helpers' {
    It 'exposes the update and ShouldProcess parameters' {
        $command = Get-Command -Name "$PSScriptRoot/../scripts/Bootstrap-Global.ps1"

        Should-HaveParameter -Actual $command -ParameterName 'Update' -Type ([switch])
        Should-HaveParameter -Actual $command -ParameterName 'WhatIf' -Type ([switch])
        Should-HaveParameter -Actual $command -ParameterName 'Confirm' -Type ([switch])
    }

    It 'recognizes only the APM marker near the start of a regular file' {
        $generatedPath = Join-Path $TestDrive 'generated.md'
        $lateMarkerPath = Join-Path $TestDrive 'late-marker.md'
        $handAuthoredPath = Join-Path $TestDrive 'hand-authored.md'

        @(
            '# AGENTS.md'
            '<!-- Generated by APM CLI from .apm/ primitives -->'
            '<!-- Build ID: test -->'
        ) | Set-Content -LiteralPath $generatedPath
        @('# one', '# two', '# three', '# four', '# five', '# six', '<!-- Generated by APM CLI from .apm/ primitives -->') |
            Set-Content -LiteralPath $lateMarkerPath
        '# Personal instructions' | Set-Content -LiteralPath $handAuthoredPath

        Test-ApmGeneratedFile -Path $generatedPath | Should-BeTrue
        Test-ApmGeneratedFile -Path $lateMarkerPath | Should-BeFalse
        Test-ApmGeneratedFile -Path $handAuthoredPath | Should-BeFalse
    }

    It 'backs up a hand-authored file once and leaves generated output in place' {
        $handAuthoredPath = Join-Path $TestDrive 'personal.md'
        $generatedPath = Join-Path $TestDrive 'generated.md'
        '# Personal instructions' | Set-Content -LiteralPath $handAuthoredPath
        @('# AGENTS.md', '<!-- Generated by APM CLI from .apm/ primitives -->') |
            Set-Content -LiteralPath $generatedPath

        Save-HandAuthoredInstructionFile -Path $handAuthoredPath -Timestamp '20260714-120000'
        Save-HandAuthoredInstructionFile -Path $generatedPath -Timestamp '20260714-120000'

        Test-Path -LiteralPath $handAuthoredPath | Should-BeFalse
        Test-Path -LiteralPath "$handAuthoredPath.backup-20260714-120000" | Should-BeTrue
        Test-Path -LiteralPath $generatedPath | Should-BeTrue
        @(Get-ChildItem -LiteralPath $TestDrive -Filter 'generated.md.backup-*').Count | Should-Be 0
    }

    It 'updates one top-level Codex setting while preserving other content' {
        $configPath = Join-Path $TestDrive '.codex/config.toml'
        $null = New-Item -ItemType Directory -Path (Split-Path -Parent $configPath)
        @(
            'model = "gpt-5"'
            'project_doc_max_bytes = 4096'
            'project_doc_max_bytes = 8192'
            ''
            '[mcp_servers.example]'
            'project_doc_max_bytes = 2048'
            'url = "https://example.invalid"'
        ) | Set-Content -LiteralPath $configPath

        Set-CodexProjectDocLimit -Path $configPath

        $content = [System.IO.File]::ReadAllText($configPath)
        ([regex]::Matches($content, '(?m)^project_doc_max_bytes = 131072$')).Count | Should-Be 1
        $content | Should-MatchString '(?m)^model = "gpt-5"$'
        $content | Should-MatchString '(?m)^\[mcp_servers\.example\]$'
        $content | Should-MatchString '(?m)^project_doc_max_bytes = 2048$'
        $content | Should-MatchString '(?m)^url = "https://example\.invalid"$'
    }

    It 'inserts the Codex setting before the first table when it is absent' {
        $configPath = Join-Path $TestDrive 'config.toml'
        @('[features]', 'enabled = true') | Set-Content -LiteralPath $configPath

        Set-CodexProjectDocLimit -Path $configPath

        $lines = [System.IO.File]::ReadAllLines($configPath)
        $lines[0] | Should-Be 'project_doc_max_bytes = 131072'
        $lines[2] | Should-Be '[features]'
        $lines[3] | Should-Be 'enabled = true'
    }

    It 'throws when an APM native command fails' {
        if ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT) {
            $fakeApm = Join-Path $TestDrive 'apm-failure.cmd'
            @('@echo off', 'exit /b 7') | Set-Content -LiteralPath $fakeApm
        }
        else {
            $fakeApm = Join-Path $TestDrive 'apm-failure'
            @('#!/bin/sh', 'exit 7') | Set-Content -LiteralPath $fakeApm
            & chmod +x $fakeApm
        }

        { Invoke-ApmCommand -Executable $fakeApm -ArgumentList @('install', '--global') } |
            Should-Throw -ExceptionMessage '*exit code 7*'
    }
}
