#!/usr/bin/env bash

set -euo pipefail

readonly GENERATED_MARKER='<!-- Generated by APM CLI from .apm/ primitives -->'
readonly BACKUP_NAMESPACE='agent-engineering-baseline'

readonly LOCAL_SKILLS=(
    a11y
    agent-safety
    ansible
    powershell-pester-6
    powershell-module-engineering
)

readonly MANAGED_SKILLS=(
    a11y
    agent-safety
    ansible
    powershell-pester-6
    powershell-module-engineering
    code-simplification
    dependabot
    git-commit
    github-actions-hardening
    msgraph
)

usage() {
    cat <<'EOF'
Usage: scripts/bootstrap-global.sh [--dry-run]

Install the pinned APM CLI when needed, then transactionally deploy this
repository's reviewed manifest, lockfile, local sources, skills, and generated
instructions at user scope.

Options:
  --dry-run  Run preflight checks and describe the deployment without changing
             the user profile.
  -h, --help Show this help text.
EOF
}

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command is not available on PATH: $1"
}

normalize_version() {
    printf '%s\n' "$1" | sed -nE 's/.*[^0-9]([0-9]+\.[0-9]+\.[0-9]+).*/\1/p'
}

get_pinned_checksum() {
    local name=$1
    local checksum

    checksum=$(
        awk -v name="$name" '
            $2 == name { checksum = $1; count++ }
            END {
                if (count != 1) exit 1
                print checksum
            }
        ' "$checksums_file"
    ) || die "Expected exactly one pinned checksum for $name."
    printf '%s\n' "$checksum" | grep -Eq '^[0-9a-f]{64}$' ||
        die "The pinned checksum for $name is not a lowercase SHA256 hex digest: $checksum"
    printf '%s\n' "$checksum"
}

verify_sha256() {
    local path=$1
    local name=$2
    local expected_hash actual_hash

    expected_hash=$(get_pinned_checksum "$name")
    actual_hash=$(sha256sum "$path" | awk '{ print $1 }')
    [ "$actual_hash" = "$expected_hash" ] ||
        die "$name does not match the pinned SHA256 checksum; refusing to execute downloaded code."
}

verify_pinned_apm_executable() {
    local executable_path=$1
    local resolved_path

    resolved_path=$(readlink -f -- "$executable_path") ||
        die "Unable to resolve the installed APM executable: $executable_path"
    assert_regular_file "$resolved_path" 'Installed APM executable'
    [ -x "$resolved_path" ] || die "Installed APM executable is not executable: $resolved_path"
    verify_sha256 "$resolved_path" "$archive_member"
    printf '%s\n' "$resolved_path"
}

run_apm() {
    verify_sha256 "$apm_executable" "$archive_member"
    "$apm_executable" "$@"
}

verify_tar_layout() {
    local archive_path=$1
    local expected_root=$2
    local expected_member=$3

    tar -tzf "$archive_path" | awk -v root="$expected_root" -v member="$expected_member" '
        BEGIN { valid = 1; member_count = 0 }
        {
            path = $0
            if (path == member) { member_count++ }
            if (path != root && index(path, root "/") != 1) { valid = 0 }
            if (path ~ /^\// || path ~ /(^|\/)\.\.($|\/)/) { valid = 0 }
        }
        END { exit(valid && member_count == 1 ? 0 : 1) }
    ' || die "Downloaded archive has an unexpected or unsafe layout: $archive_path"
}

assert_regular_file() {
    local path=$1
    local label=$2

    [ ! -L "$path" ] || die "$label is a symbolic link: $path"
    [ -f "$path" ] || die "$label is not a regular file: $path"
}

assert_directory_without_links() {
    local path=$1
    local label=$2
    local linked_path

    [ ! -L "$path" ] || die "$label is a symbolic link: $path"
    [ -d "$path" ] || die "$label is not a directory: $path"
    linked_path=$(find "$path" -type l -print -quit)
    [ -z "$linked_path" ] || die "$label contains a symbolic link: $linked_path"
}

assert_safe_existing_target() {
    local path=$1
    local expected_type=${2-}
    local linked_path

    if [ -L "$path" ]; then
        die "Refusing to manage symbolic-link target: $path"
    fi

    if [ ! -e "$path" ]; then
        return
    fi

    case "$expected_type" in
        file)
            [ -f "$path" ] || die "Managed target is not a regular file: $path"
            ;;
        directory)
            [ -d "$path" ] || die "Managed target is not a directory: $path"
            ;;
        tree)
            [ -d "$path" ] || die "Managed target is not a directory: $path"
            linked_path=$(find "$path" -type l -print -quit)
            [ -z "$linked_path" ] || die "Managed target contains a symbolic link: $linked_path"
            ;;
    esac
}

is_apm_generated() {
    local path=$1

    [ ! -L "$path" ] || return 1
    [ -f "$path" ] || return 1

    awk -v marker="$GENERATED_MARKER" '
        NR <= 6 && $0 == marker { found = 1 }
        END { exit(found ? 0 : 1) }
    ' "$path"
}

copy_path() {
    local source_path=$1
    local destination_path=$2

    mkdir -p "$(dirname "$destination_path")"
    cp -a -- "$source_path" "$destination_path"
}

remove_path() {
    local path=$1

    if [ -e "$path" ] || [ -L "$path" ]; then
        rm -rf -- "$path"
    fi
}

replace_path() {
    local source_path=$1
    local destination_path=$2
    local staged_path="${destination_path}.agent-baseline-stage-$$"

    if [ -e "$staged_path" ] || [ -L "$staged_path" ]; then
        die "Temporary replacement path already exists: $staged_path"
    fi
    mkdir -p "$(dirname "$destination_path")"
    copy_path "$source_path" "$staged_path"
    remove_path "$destination_path"
    mv -- "$staged_path" "$destination_path"
}

snapshot_path() {
    local relative_path=$1
    local source_path="$home_path/$relative_path"
    local snapshot_path="$snapshot_root/$relative_path"

    if [ -e "$source_path" ] || [ -L "$source_path" ]; then
        printf 'present\t%s\n' "$relative_path" >> "$inventory_path"
        copy_path "$source_path" "$snapshot_path"
    else
        printf 'absent\t%s\n' "$relative_path" >> "$inventory_path"
        printf '%s\n' "$relative_path" >> "$absent_path"
    fi
}

restore_snapshot() {
    local status
    local relative_path
    local destination_path
    local snapshot_path
    local restore_failed=false

    [ -n "${inventory_path-}" ] && [ -f "$inventory_path" ] || return 0

    while IFS=$'\t' read -r status relative_path; do
        [ -n "$relative_path" ] || continue
        destination_path="$home_path/$relative_path"
        snapshot_path="$snapshot_root/$relative_path"

        if ! remove_path "$destination_path"; then
            restore_failed=true
            continue
        fi
        if [ "$status" = present ] && ! copy_path "$snapshot_path" "$destination_path"; then
            restore_failed=true
        fi
    done < "$inventory_path"

    [ "$restore_failed" = false ]
}

on_exit() {
    local exit_code=$?

    trap - EXIT HUP INT TERM
    if [ -n "${preflight_temp-}" ] && [ -d "$preflight_temp" ]; then
        rm -rf -- "$preflight_temp"
    fi
    if [ -n "${cli_temp-}" ] && [ -d "$cli_temp" ]; then
        rm -rf -- "$cli_temp"
    fi

    if [ "$exit_code" -ne 0 ] && [ "${mutation_started-false}" = true ]; then
        printf 'Deployment failed; restoring snapshot: %s\n' "$backup_dir" >&2
        if restore_snapshot; then
            printf 'Rollback completed successfully. Snapshot retained at: %s\n' "$backup_dir" >&2
        else
            printf 'Rollback encountered errors. Preserve and inspect: %s\n' "$backup_dir" >&2
        fi
    fi

    exit "$exit_code"
}

dry_run=false
while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            [ "$dry_run" = false ] || die '--dry-run may be specified only once.'
            dry_run=true
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
    shift
done

for command_name in awk chmod cmp cp date diff dirname find grep head mkdir mktemp mv readlink rm sed sh tar tr uname wc; do
    require_command "$command_name"
done

script_dir=$(CDPATH='' cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
repo_root=$(CDPATH='' cd -- "$script_dir/.." && pwd -P)
manifest_path="$repo_root/apm.yml"
lockfile_path="$repo_root/apm.lock.yaml"
source_apm_path="$repo_root/.apm"
version_file="$repo_root/.apm-version"
checksums_file="$repo_root/.apm-checksums"
home_path=${HOME:?HOME must be set.}

[ ! -L "$home_path" ] || die "HOME must not be a symbolic link: $home_path"
[ -d "$home_path" ] || die "HOME is not a directory: $home_path"
assert_regular_file "$manifest_path" 'Repository APM manifest'
assert_regular_file "$lockfile_path" 'Repository APM lockfile'
assert_regular_file "$version_file" 'Repository APM version pin'
assert_regular_file "$checksums_file" 'Repository APM checksums'
assert_directory_without_links "$source_apm_path" 'Repository local APM source'

for skill_name in "${LOCAL_SKILLS[@]}"; do
    skill_source="$source_apm_path/skills/$skill_name"
    assert_directory_without_links "$skill_source" "Local skill source '$skill_name'"
    assert_regular_file "$skill_source/SKILL.md" "Local skill entrypoint '$skill_name'"
done

approved_version=$(head -n 1 "$version_file" | tr -d '[:space:]')
printf '%s\n' "$approved_version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' ||
    die "The APM version pin is not a plain X.Y.Z version: $approved_version"

[ "$(uname -s)" = Linux ] || die 'This bootstrap supports Linux; use Bootstrap-Global.ps1 on Windows.'
case "$(uname -m)" in
    x86_64)
        platform_arch=x86_64
        ;;
    arm64|aarch64)
        platform_arch=arm64
        ;;
    *)
        die "Unsupported Linux architecture: $(uname -m)"
        ;;
esac
archive_name="apm-linux-$platform_arch.tar.gz"
archive_root="apm-linux-$platform_arch"
archive_member="$archive_root/apm"

apm_action=install
installed_version=''
if command -v apm >/dev/null 2>&1; then
    require_command sha256sum
    apm_executable=$(verify_pinned_apm_executable "$(command -v apm)")
    installed_version=$(normalize_version "$(run_apm --version)")
    [ "$installed_version" = "$approved_version" ] ||
        die "Installed APM executable matches the reviewed digest but reports version ${installed_version:-unknown}; expected $approved_version."
    apm_action=none
fi

global_apm_dir="$home_path/.apm"
codex_dir="$home_path/.codex"
copilot_dir="$home_path/.copilot"
agents_dir="$home_path/.agents"
backup_base="$global_apm_dir/backups/$BACKUP_NAMESPACE"

assert_safe_existing_target "$global_apm_dir" directory
assert_safe_existing_target "$codex_dir" directory
assert_safe_existing_target "$copilot_dir" directory
assert_safe_existing_target "$agents_dir" directory
assert_safe_existing_target "$agents_dir/skills" directory
assert_safe_existing_target "$global_apm_dir/backups" directory
assert_safe_existing_target "$backup_base" directory
assert_safe_existing_target "$global_apm_dir/apm.yml" file
assert_safe_existing_target "$global_apm_dir/apm.lock.yaml" file
assert_safe_existing_target "$global_apm_dir/.apm" tree
assert_safe_existing_target "$global_apm_dir/apm_modules" tree
assert_safe_existing_target "$global_apm_dir/config.json" file
assert_safe_existing_target "$codex_dir/AGENTS.md" file
assert_safe_existing_target "$copilot_dir/copilot-instructions.md" file
for skill_name in "${MANAGED_SKILLS[@]}"; do
    assert_safe_existing_target "$agents_dir/skills/$skill_name" tree
done

preflight_temp=$(mktemp -d "${TMPDIR:-/tmp}/agent-baseline-preflight.XXXXXX")
mutation_started=false
trap on_exit EXIT HUP INT TERM

if [ "$dry_run" = true ]; then
    printf 'Dry run: APM CLI action: %s (pinned version %s' "$apm_action" "$approved_version"
    [ -z "$installed_version" ] || printf ', installed version %s' "$installed_version"
    printf ').\n'
    printf '%s\n' 'Dry run: preflight checks passed; no user-profile files were changed.'
    printf '%s\n' 'Dry run: would copy the reviewed manifest, lockfile, and local .apm sources.'
    printf '%s\n' 'Dry run: would run apm install --global --frozen and compile Codex/Copilot instructions.'
    exit 0
fi

if [ "$apm_action" != none ]; then
    require_command curl
    require_command sha256sum
    cli_temp=$(mktemp -d "${TMPDIR:-/tmp}/apm-install.XXXXXX")
    installer_path="$cli_temp/install.sh"
    archive_path="$cli_temp/$archive_name"
    curl --fail --location --silent --show-error --output "$installer_path" \
        "https://raw.githubusercontent.com/microsoft/apm/v$approved_version/install.sh"
    curl --fail --location --silent --show-error --output "$archive_path" \
        "https://github.com/microsoft/apm/releases/download/v$approved_version/$archive_name"
    verify_sha256 "$installer_path" 'install.sh'
    verify_sha256 "$archive_path" "$archive_name"
    verify_tar_layout "$archive_path" "$archive_root" "$archive_member"
    archive_check_dir="$cli_temp/archive-check"
    mkdir "$archive_check_dir"
    tar -xzf "$archive_path" -C "$archive_check_dir"
    assert_directory_without_links "$archive_check_dir/$archive_root" 'Downloaded APM bundle'
    assert_regular_file "$archive_check_dir/$archive_member" 'Downloaded APM executable'
    verify_sha256 "$archive_check_dir/$archive_member" "$archive_member"
    mirror_tag_dir="$cli_temp/mirror/v$approved_version"
    mkdir -p "$mirror_tag_dir"
    cp -- "$archive_path" "$mirror_tag_dir/$archive_name"
    verify_sha256 "$mirror_tag_dir/$archive_name" "$archive_name"
    VERSION="v$approved_version" \
        APM_RELEASE_BASE_URL="file://$cli_temp/mirror" \
        APM_NO_DIRECT_FALLBACK=1 \
        sh "$installer_path"
    hash -r
    if ! command -v apm >/dev/null 2>&1; then
        for candidate in "${APM_INSTALL_DIR-}" "$home_path/.local/bin" /usr/local/bin; do
            [ -n "$candidate" ] || continue
            if [ -x "$candidate/apm" ]; then
                PATH="$candidate:$PATH"
                export PATH
                break
            fi
        done
        hash -r
    fi
    require_command apm
    apm_executable=$(verify_pinned_apm_executable "$(command -v apm)")
    verified_version=$(normalize_version "$(run_apm --version)")
    [ "$verified_version" = "$approved_version" ] ||
        die "APM installation completed but version $approved_version is not active."
    rm -rf -- "$cli_temp"
    cli_temp=''
fi

require_command apm
require_command sha256sum
if [ -z "${apm_executable-}" ]; then
    apm_executable=$(verify_pinned_apm_executable "$(command -v apm)")
fi

mkdir -p "$backup_base"
assert_safe_existing_target "$backup_base" directory
timestamp=$(date -u '+%Y%m%dT%H%M%SZ')
backup_dir="$backup_base/$timestamp"
counter=0
while [ -e "$backup_dir" ] || [ -L "$backup_dir" ]; do
    counter=$((counter + 1))
    backup_dir="$backup_base/${timestamp}-$counter"
done
snapshot_root="$backup_dir/snapshot"
inventory_path="$backup_dir/inventory.tsv"
absent_path="$backup_dir/originally-absent.txt"
staging_root="$backup_dir/staging"

mkdir -p "$snapshot_root" "$staging_root"
: > "$inventory_path"
: > "$absent_path"

managed_paths=(
    '.apm/apm.yml'
    '.apm/apm.lock.yaml'
    '.apm/.apm'
    '.apm/apm_modules'
    '.apm/config.json'
    '.codex/AGENTS.md'
    '.copilot/copilot-instructions.md'
)
for skill_name in "${MANAGED_SKILLS[@]}"; do
    managed_paths+=(".agents/skills/$skill_name")
done
for relative_path in "${managed_paths[@]}"; do
    snapshot_path "$relative_path"
done

copy_path "$manifest_path" "$staging_root/apm.yml"
copy_path "$lockfile_path" "$staging_root/apm.lock.yaml"
copy_path "$source_apm_path" "$staging_root/.apm"
cmp -s "$manifest_path" "$staging_root/apm.yml" || die 'Staged APM manifest verification failed.'
cmp -s "$lockfile_path" "$staging_root/apm.lock.yaml" || die 'Staged APM lockfile verification failed.'
diff -qr "$source_apm_path" "$staging_root/.apm" >/dev/null || die 'Staged local APM source verification failed.'

mutation_started=true
replace_path "$staging_root/apm.yml" "$global_apm_dir/apm.yml"
replace_path "$staging_root/apm.lock.yaml" "$global_apm_dir/apm.lock.yaml"
replace_path "$staging_root/.apm" "$global_apm_dir/.apm"

remove_path "$codex_dir/AGENTS.md"
remove_path "$copilot_dir/copilot-instructions.md"
for skill_name in "${MANAGED_SKILLS[@]}"; do
    remove_path "$agents_dir/skills/$skill_name"
done

run_apm install --global --frozen

for skill_name in "${LOCAL_SKILLS[@]}"; do
    replace_path "$global_apm_dir/.apm/skills/$skill_name" "$agents_dir/skills/$skill_name"
done

(
    cd "$global_apm_dir"
    run_apm compile --target codex --single-agents --output "$codex_dir/AGENTS.md" --dry-run
    run_apm compile --target copilot --single-agents --output "$copilot_dir/copilot-instructions.md" --dry-run
    run_apm compile --target codex --single-agents --output "$codex_dir/AGENTS.md"
    run_apm compile --target copilot --single-agents --output "$copilot_dir/copilot-instructions.md"
)

cmp -s "$manifest_path" "$global_apm_dir/apm.yml" || die 'Deployed APM manifest differs from the reviewed source.'
diff -I '^generated_at:' "$lockfile_path" "$global_apm_dir/apm.lock.yaml" >/dev/null ||
    die 'Deployed APM lockfile differs from the reviewed source.'
diff -qr "$source_apm_path" "$global_apm_dir/.apm" >/dev/null ||
    die 'Deployed local APM sources differ from the reviewed source.'

for skill_name in "${LOCAL_SKILLS[@]}"; do
    diff -qr "$source_apm_path/skills/$skill_name" "$agents_dir/skills/$skill_name" >/dev/null ||
        die "Deployed local skill differs from its reviewed source: $skill_name"
done
for skill_name in "${MANAGED_SKILLS[@]}"; do
    [ -d "$agents_dir/skills/$skill_name" ] || die "Managed skill was not deployed: $skill_name"
done

is_apm_generated "$codex_dir/AGENTS.md" || die 'Codex instructions do not contain the expected APM marker.'
is_apm_generated "$copilot_dir/copilot-instructions.md" ||
    die 'Copilot instructions do not contain the expected APM marker.'

mutation_started=false
printf '%s\n' 'Global APM configuration is ready.'
printf 'Rollback snapshot retained at: %s\n' "$backup_dir"
printf '%s\n' 'Start new Codex and Copilot sessions to load the updated configuration.'
