<#
.SYNOPSIS
Installs and transactionally deploys the reviewed global APM baseline.

.DESCRIPTION
Installs or upgrades the repository-pinned APM CLI when needed, preflights the
reviewed manifest, lockfile, local sources, and managed destinations, creates a
complete timestamped rollback snapshot, runs a frozen global installation,
deploys the local skills, and compiles Codex and Copilot instructions through
dry-run validation before writing them.

An existing github-mcp-server entry is removed only when every Codex or Copilot
setting matches the reviewed legacy definition. Any failure after profile
mutation begins restores the snapshot automatically. Successful snapshots are
retained for manual rollback.

.EXAMPLE
./scripts/Bootstrap-Global.ps1

Deploys the reviewed global baseline.

.EXAMPLE
./scripts/Bootstrap-Global.ps1 -WhatIf

Runs preflight checks and describes the deployment without changing the user
profile.

.OUTPUTS
None. The script writes deployment status to the information stream.

.NOTES
The script supports Windows PowerShell 5.1 and PowerShell 7. It never reads,
writes, or displays GITHUB_TOKEN and does not manage project_doc_max_bytes or
~/.copilot/AGENTS.md.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param()

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$script:GeneratedMarker = '<!-- Generated by APM CLI from .apm/ primitives -->'
$script:GithubMcpName = 'github-mcp-server'
$script:GithubMcpUrl = 'https://api.githubcopilot.com/mcp/'
$script:BackupNamespace = 'agent-engineering-baseline'
$script:LocalSkills = @(
    'a11y'
    'agent-safety'
    'ansible'
    'powershell-pester-6'
    'powershell-module-engineering'
)
$script:ManagedSkills = @(
    'a11y'
    'agent-safety'
    'ansible'
    'powershell-pester-6'
    'powershell-module-engineering'
    'code-simplification'
    'dependabot'
    'git-commit'
    'github-actions-hardening'
    'msgraph'
)

function Test-ReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.IO.FileSystemInfo]$Item
    )

    return (($Item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0)
}

function Test-PathWithoutReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [ValidateSet('File', 'Directory')]
        [string]$PathType,

        [Parameter()]
        [switch]$AllowMissing,

        [Parameter()]
        [switch]$Recurse
    )

    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) {
        if ($AllowMissing.IsPresent) {
            return $true
        }
        return $false
    }

    if (Test-ReparsePoint -Item $item) {
        return $false
    }

    if ($PathType -eq 'File') {
        return (-not $item.PSIsContainer)
    }
    if (-not $item.PSIsContainer) {
        return $false
    }

    if ($Recurse.IsPresent) {
        $linkedItem = Get-ChildItem -LiteralPath $Path -Force -Recurse `
            -Attributes ReparsePoint -ErrorAction Stop |
            Select-Object -First 1
        return ($null -eq $linkedItem)
    }
    return $true
}

function Assert-PathWithoutReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [ValidateSet('File', 'Directory')]
        [string]$PathType,

        [Parameter()]
        [switch]$AllowMissing,

        [Parameter()]
        [switch]$Recurse,

        [Parameter(Mandatory)]
        [string]$Description
    )

    if (-not (Test-PathWithoutReparsePoint -Path $Path -PathType $PathType `
            -AllowMissing:$AllowMissing -Recurse:$Recurse)) {
        throw "$Description is missing, has the wrong type, or contains a reparse point: $Path"
    }
}

function Test-ApmGeneratedFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-PathWithoutReparsePoint -Path $Path -PathType File -AllowMissing)) {
        return $false
    }
    if (-not [System.IO.File]::Exists($Path)) {
        return $false
    }

    $reader = [System.IO.File]::OpenText($Path)
    try {
        $lineNumber = 0
        while (-not $reader.EndOfStream -and $lineNumber -lt 6) {
            $line = $reader.ReadLine()
            $lineNumber++
            if ($line -ceq $script:GeneratedMarker) {
                return $true
            }
        }
        return $false
    }
    finally {
        $reader.Dispose()
    }
}

function Get-ProjectDocSetting {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not [System.IO.File]::Exists($Path)) {
        return
    }

    $reader = [System.IO.File]::OpenText($Path)
    try {
        while (-not $reader.EndOfStream) {
            $line = $reader.ReadLine()
            if ($line -match '^\s*\[') {
                break
            }
            if ($line -match '^\s*project_doc_max_bytes\s*=') {
                Write-Output $line
            }
        }
    }
    finally {
        $reader.Dispose()
    }
}

function Test-DefaultGithubMcpConfiguration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object]$Configuration
    )

    $expectedTopLevel = @(
        'disabled_reason', 'disabled_tools', 'enabled', 'enabled_tools', 'name',
        'startup_timeout_sec', 'tool_timeout_sec', 'transport'
    ) -join ','
    $actualTopLevel = @($Configuration.PSObject.Properties.Name | Sort-Object) -join ','
    if ($actualTopLevel -cne $expectedTopLevel) {
        return $false
    }

    $expectedTransport = @(
        'bearer_token_env_var', 'env_http_headers', 'http_headers',
        'http_headers_helper', 'type', 'url'
    ) -join ','
    $actualTransport = @($Configuration.transport.PSObject.Properties.Name | Sort-Object) -join ','

    return (
        $actualTransport -ceq $expectedTransport -and
        $Configuration.name -ceq $script:GithubMcpName -and
        $Configuration.enabled -eq $true -and
        $null -eq $Configuration.disabled_reason -and
        $null -eq $Configuration.enabled_tools -and
        $null -eq $Configuration.disabled_tools -and
        $null -eq $Configuration.startup_timeout_sec -and
        $null -eq $Configuration.tool_timeout_sec -and
        $Configuration.transport.type -ceq 'streamable_http' -and
        $Configuration.transport.url -ceq $script:GithubMcpUrl -and
        $Configuration.transport.bearer_token_env_var -ceq 'GITHUB_TOKEN' -and
        $null -eq $Configuration.transport.http_headers -and
        $null -eq $Configuration.transport.env_http_headers -and
        $null -eq $Configuration.transport.http_headers_helper
    )
}

function Test-DefaultCopilotGithubMcpConfiguration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object]$Configuration
    )

    $expectedProperties = @(
        'bearer_token_env_var', 'headers', 'id', 'tools', 'type', 'url'
    ) -join ','
    $actualProperties = @($Configuration.PSObject.Properties.Name | Sort-Object) -join ','
    $headerCount = if ($null -eq $Configuration.headers) {
        -1
    }
    else {
        @($Configuration.headers.PSObject.Properties).Count
    }
    $tools = @($Configuration.tools)

    return (
        $actualProperties -ceq $expectedProperties -and
        $Configuration.type -ceq 'http' -and
        $Configuration.url -ceq $script:GithubMcpUrl -and
        $tools.Count -eq 1 -and
        $tools[0] -ceq '*' -and
        $Configuration.id -ceq '' -and
        $headerCount -eq 0 -and
        $Configuration.bearer_token_env_var -ceq 'GITHUB_TOKEN'
    )
}

function ConvertTo-ApmVersion {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Text)

    $match = [regex]::Match($Text, '(?<!\d)(\d+\.\d+\.\d+)(?!\d)')
    if (-not $match.Success) { throw "Unable to parse APM version from: $Text" }
    return [version]$match.Groups[1].Value
}

function Get-ApmBootstrapAction {
    [CmdletBinding()]
    param(
        [Parameter()][AllowNull()][version]$InstalledVersion,
        [Parameter(Mandatory)][version]$ApprovedVersion
    )

    if ($null -eq $InstalledVersion) { return 'Install' }
    if ($InstalledVersion -gt $ApprovedVersion) { return 'Stop' }
    if ($InstalledVersion -lt $ApprovedVersion) { return 'Upgrade' }
    return 'None'
}

function Get-PinnedInstallerChecksum {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ChecksumPath,
        [Parameter(Mandatory)][string]$FileName
    )

    if (-not (Test-Path -LiteralPath $ChecksumPath -PathType Leaf)) {
        throw "Missing APM installer checksums: $ChecksumPath"
    }
    $pattern = '^\s*([0-9a-fA-F]{64})\s+\*?' + [regex]::Escape($FileName) + '\s*$'
    foreach ($line in @([System.IO.File]::ReadAllLines($ChecksumPath))) {
        $match = [regex]::Match($line, $pattern)
        if ($match.Success) { return $match.Groups[1].Value }
    }
    throw "No pinned SHA256 checksum for $FileName in $ChecksumPath"
}

function Update-ProcessPath {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param()

    if (-not $PSCmdlet.ShouldProcess('process PATH', 'Merge machine and user PATH entries')) { return }
    $separator = [IO.Path]::PathSeparator
    $current = @($env:PATH -split [regex]::Escape($separator))
    foreach ($scope in @('Machine', 'User')) {
        $scoped = [Environment]::GetEnvironmentVariable('Path', $scope)
        if ([string]::IsNullOrWhiteSpace($scoped)) { continue }
        foreach ($entry in @($scoped -split [regex]::Escape($separator))) {
            if (-not [string]::IsNullOrWhiteSpace($entry) -and $current -notcontains $entry) {
                $env:PATH = "$($env:PATH)$separator$entry"
                $current += $entry
            }
        }
    }
}

function Invoke-ExternalCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Executable,

        [Parameter(Mandatory)]
        [string[]]$ArgumentList,

        [Parameter()]
        [string]$WorkingDirectory
    )

    $pushed = $false
    try {
        if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) {
            Push-Location -LiteralPath $WorkingDirectory
            $pushed = $true
        }
        & $Executable @ArgumentList
        if ($LASTEXITCODE -ne 0) {
            $renderedArguments = $ArgumentList -join ' '
            throw "Native command failed with exit code ${LASTEXITCODE}: $Executable $renderedArguments"
        }
    }
    finally {
        if ($pushed) {
            Pop-Location
        }
    }
}

function Copy-ManagedPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Source,

        [Parameter(Mandatory)]
        [string]$Destination
    )

    $parentPath = Split-Path -Parent $Destination
    if (-not (Test-Path -LiteralPath $parentPath -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $parentPath -Force
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
}

function Remove-ManagedPath {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if ((Test-Path -LiteralPath $Path) -and $PSCmdlet.ShouldProcess($Path, 'Remove managed path')) {
        Remove-Item -LiteralPath $Path -Recurse -Force
    }
}

function Set-ManagedPath {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)]
        [string]$Source,

        [Parameter(Mandatory)]
        [string]$Destination
    )

    if ($PSCmdlet.ShouldProcess($Destination, 'Replace managed path')) {
        $stagedPath = '{0}.agent-baseline-stage-{1}' -f $Destination, [Guid]::NewGuid().ToString('N')
        Copy-ManagedPath -Source $Source -Destination $stagedPath
        try {
            Remove-ManagedPath -Path $Destination -Confirm:$false
            Move-Item -LiteralPath $stagedPath -Destination $Destination
        }
        finally {
            if (Test-Path -LiteralPath $stagedPath) {
                Remove-ManagedPath -Path $stagedPath -Confirm:$false
            }
        }
    }
}

function Get-DirectoryInventory {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    $root = [System.IO.Path]::GetFullPath($Path).TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar
    )
    $items = @(Get-ChildItem -LiteralPath $root -Force -Recurse | Sort-Object -Property FullName)
    foreach ($item in $items) {
        $relativePath = $item.FullName.Substring($root.Length).TrimStart(
            [System.IO.Path]::DirectorySeparatorChar,
            [System.IO.Path]::AltDirectorySeparatorChar
        )
        if ($item.PSIsContainer) {
            Write-Output "D`t$relativePath"
        }
        else {
            $hash = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash
            Write-Output "F`t$relativePath`t$hash"
        }
    }
}

function Test-DirectoryContentEqual {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ReferencePath,

        [Parameter(Mandatory)]
        [string]$DifferencePath
    )

    if (-not (Test-Path -LiteralPath $ReferencePath -PathType Container) -or
        -not (Test-Path -LiteralPath $DifferencePath -PathType Container)) {
        return $false
    }

    $reference = @(Get-DirectoryInventory -Path $ReferencePath)
    $difference = @(Get-DirectoryInventory -Path $DifferencePath)
    return (($reference -join "`n") -ceq ($difference -join "`n"))
}

function Test-LockfileContentEqual {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ReferencePath,

        [Parameter(Mandatory)]
        [string]$DifferencePath
    )

    if (-not [System.IO.File]::Exists($ReferencePath) -or
        -not [System.IO.File]::Exists($DifferencePath)) {
        return $false
    }

    $reference = @([System.IO.File]::ReadAllLines($ReferencePath) | Where-Object { $_ -notmatch '^generated_at:' })
    $difference = @([System.IO.File]::ReadAllLines($DifferencePath) | Where-Object { $_ -notmatch '^generated_at:' })
    return (($reference -join "`n") -ceq ($difference -join "`n"))
}

function Save-GlobalSnapshotPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$RelativePath,

        [Parameter(Mandatory)]
        [string]$SnapshotRoot,

        [Parameter(Mandatory)]
        [string]$InventoryPath,

        [Parameter(Mandatory)]
        [string]$AbsentPath
    )

    $sourcePath = Join-Path -Path $HomePath -ChildPath $RelativePath
    if (Test-Path -LiteralPath $sourcePath) {
        Add-Content -LiteralPath $InventoryPath -Value "present`t$RelativePath" -Encoding UTF8
        Copy-ManagedPath -Source $sourcePath -Destination (Join-Path $SnapshotRoot $RelativePath)
    }
    else {
        Add-Content -LiteralPath $InventoryPath -Value "absent`t$RelativePath" -Encoding UTF8
        Add-Content -LiteralPath $AbsentPath -Value $RelativePath -Encoding UTF8
    }
}

function Restore-GlobalSnapshot {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$SnapshotRoot,

        [Parameter(Mandatory)]
        [string]$InventoryPath
    )

    foreach ($line in [System.IO.File]::ReadAllLines($InventoryPath)) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }
        $fields = $line -split "`t", 2
        $status = $fields[0].TrimStart([char]0xFEFF)
        $relativePath = $fields[1]
        $destinationPath = Join-Path -Path $HomePath -ChildPath $relativePath
        Remove-ManagedPath -Path $destinationPath -Confirm:$false
        if ($status -ceq 'present') {
            Copy-ManagedPath -Source (Join-Path $SnapshotRoot $relativePath) -Destination $destinationPath
        }
    }
}

function Get-ExplicitConfirmParameter {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Collections.IDictionary]$BoundParameters
    )

    $result = @{}
    if ($BoundParameters.Contains('Confirm')) {
        $result['Confirm'] = [bool]$BoundParameters['Confirm']
    }
    return $result
}

function Invoke-GlobalBootstrap {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$RepositoryRoot
    )

    $codexCommand = @(Get-Command -Name codex -CommandType Application -ErrorAction SilentlyContinue)[0]
    if ($null -eq $codexCommand) {
        throw 'Required command is not available on PATH: codex'
    }

    $manifestPath = Join-Path -Path $RepositoryRoot -ChildPath 'apm.yml'
    $lockfilePath = Join-Path -Path $RepositoryRoot -ChildPath 'apm.lock.yaml'
    $sourceApmPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm'
    $versionPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm-version'
    $checksumPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm-installer-checksums'
    Assert-PathWithoutReparsePoint -Path $HomePath -PathType Directory -Description 'HOME'
    Assert-PathWithoutReparsePoint -Path $manifestPath -PathType File -Description 'Repository APM manifest'
    Assert-PathWithoutReparsePoint -Path $lockfilePath -PathType File -Description 'Repository APM lockfile'
    Assert-PathWithoutReparsePoint -Path $versionPath -PathType File -Description 'Repository APM version pin'
    Assert-PathWithoutReparsePoint -Path $checksumPath -PathType File `
        -Description 'Repository APM installer checksums'
    Assert-PathWithoutReparsePoint -Path $sourceApmPath -PathType Directory -Recurse `
        -Description 'Repository local APM source'
    foreach ($skillName in $script:LocalSkills) {
        $skillSource = Join-Path -Path $sourceApmPath -ChildPath "skills/$skillName"
        Assert-PathWithoutReparsePoint -Path $skillSource -PathType Directory -Recurse `
            -Description "Local skill source '$skillName'"
        Assert-PathWithoutReparsePoint -Path (Join-Path $skillSource 'SKILL.md') -PathType File `
            -Description "Local skill entrypoint '$skillName'"
    }

    $pinText = ([System.IO.File]::ReadAllLines($versionPath)[0]).Trim()
    if ($pinText -notmatch '^\d+\.\d+\.\d+$') {
        throw "The APM version pin is not a plain X.Y.Z version: $pinText"
    }
    $approvedVersion = [version]$pinText
    $apmCommand = @(Get-Command -Name apm -CommandType Application -ErrorAction SilentlyContinue)[0]
    $installedVersion = $null
    if ($null -ne $apmCommand) {
        $installedVersion = ConvertTo-ApmVersion -Text ((& $apmCommand.Source --version 2>&1) -join "`n")
    }
    $apmAction = Get-ApmBootstrapAction -InstalledVersion $installedVersion `
        -ApprovedVersion $approvedVersion
    if ($apmAction -ceq 'Stop') {
        throw "Installed APM $installedVersion is newer than pinned baseline $approvedVersion; deployment stopped."
    }

    $globalApmDirectory = Join-Path -Path $HomePath -ChildPath '.apm'
    $codexDirectory = Join-Path -Path $HomePath -ChildPath '.codex'
    $copilotDirectory = Join-Path -Path $HomePath -ChildPath '.copilot'
    $agentsDirectory = Join-Path -Path $HomePath -ChildPath '.agents'
    $managedTargets = @(
        @{ Path = $globalApmDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $codexDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $copilotDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $agentsDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $agentsDirectory 'skills'); Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'backups'); Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'apm.yml'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'apm.lock.yaml'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory '.apm'); Type = 'Directory'; Recurse = $true }
        @{ Path = (Join-Path $globalApmDirectory 'apm_modules'); Type = 'Directory'; Recurse = $true }
        @{ Path = (Join-Path $globalApmDirectory 'config.json'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $codexDirectory 'AGENTS.md'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $codexDirectory 'config.toml'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $copilotDirectory 'copilot-instructions.md'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $copilotDirectory 'mcp-config.json'); Type = 'File'; Recurse = $false }
    )
    foreach ($skillName in $script:ManagedSkills) {
        $managedTargets += @{
            Path = (Join-Path $agentsDirectory "skills/$skillName")
            Type = 'Directory'
            Recurse = $true
        }
    }
    foreach ($target in $managedTargets) {
        Assert-PathWithoutReparsePoint -Path $target.Path -PathType $target.Type -AllowMissing `
            -Recurse:$target.Recurse `
            -Description 'Managed target'
    }

    $preflightDirectory = Join-Path -Path ([System.IO.Path]::GetTempPath()) `
        -ChildPath ('agent-baseline-preflight-{0}' -f [Guid]::NewGuid().ToString('N'))
    $null = [System.IO.Directory]::CreateDirectory($preflightDirectory)
    $mcpJsonPath = Join-Path $preflightDirectory 'github-mcp.json'
    $mcpErrorPath = Join-Path $preflightDirectory 'github-mcp.err'
    $codexMcpRemove = $false
    try {
        $savedErrorActionPreference = $ErrorActionPreference
        $savedWhatIfPreference = $WhatIfPreference
        try {
            $ErrorActionPreference = 'Continue'
            $WhatIfPreference = $false
            & $codexCommand.Source mcp get $script:GithubMcpName --json 1> $mcpJsonPath 2> $mcpErrorPath
            $mcpExitCode = $LASTEXITCODE
        }
        finally {
            $ErrorActionPreference = $savedErrorActionPreference
            $WhatIfPreference = $savedWhatIfPreference
        }
        if ($mcpExitCode -eq 0) {
            $configuration = Get-Content -LiteralPath $mcpJsonPath -Raw | ConvertFrom-Json
            if (-not (Test-DefaultGithubMcpConfiguration -Configuration $configuration)) {
                throw "Existing Codex MCP entry '$($script:GithubMcpName)' is customized; refusing to replace it."
            }
            $codexMcpRemove = $true
        }

        $copilotConfigPath = Join-Path $copilotDirectory 'mcp-config.json'
        $cleanedCopilotConfigPath = Join-Path $preflightDirectory 'copilot-mcp-config.json'
        $copilotMcpRemove = $false
        if ([System.IO.File]::Exists($copilotConfigPath)) {
            $copilotConfigText = [System.IO.File]::ReadAllText($copilotConfigPath)
            if ($copilotConfigText.IndexOf('"github-mcp-server"', [StringComparison]::Ordinal) -ge 0) {
                $copilotConfiguration = $copilotConfigText | ConvertFrom-Json
                $mcpServersProperty = $copilotConfiguration.PSObject.Properties['mcpServers']
                $githubProperty = if ($null -eq $mcpServersProperty) {
                    $null
                }
                else {
                    $mcpServersProperty.Value.PSObject.Properties[$script:GithubMcpName]
                }
                if ($null -eq $githubProperty -or
                    -not (Test-DefaultCopilotGithubMcpConfiguration -Configuration $githubProperty.Value)) {
                    throw "Existing Copilot MCP entry '$($script:GithubMcpName)' is customized; refusing to remove it."
                }
                $mcpServersProperty.Value.PSObject.Properties.Remove($script:GithubMcpName)
                $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
                [System.IO.File]::WriteAllText(
                    $cleanedCopilotConfigPath,
                    (($copilotConfiguration | ConvertTo-Json -Depth 100) + "`n"),
                    $utf8NoBom
                )
                $copilotMcpRemove = $true
            }
        }
        else {
            $mcpError = Get-Content -LiteralPath $mcpErrorPath -Raw
            $expectedError = "No MCP server named '$($script:GithubMcpName)' found."
            if ($mcpError.IndexOf($expectedError, [StringComparison]::Ordinal) -lt 0) {
                throw "Unable to inspect the existing Codex MCP entry '$($script:GithubMcpName)'."
            }
        }

        $projectDocSettingBefore = @(
            Get-ProjectDocSetting -Path (Join-Path $codexDirectory 'config.toml')
        ) -join "`n"

        if (-not $PSCmdlet.ShouldProcess($HomePath, 'Deploy the reviewed global APM baseline')) {
            Write-Information -MessageData (
                "Dry run: APM CLI action: $apmAction (pinned version $approvedVersion)."
            ) -InformationAction Continue
            Write-Information -MessageData 'Preflight checks passed; no user-profile files were changed.' `
                -InformationAction Continue
            if ($codexMcpRemove) {
                Write-Information -MessageData (
                    "Would remove the exact reviewed Codex MCP entry '$($script:GithubMcpName)'."
                ) -InformationAction Continue
            }
            if ($copilotMcpRemove) {
                Write-Information -MessageData (
                    "Would remove the exact reviewed Copilot MCP entry '$($script:GithubMcpName)'."
                ) -InformationAction Continue
            }
            return
        }

        if ($apmAction -ne 'None') {
            $expectedHash = Get-PinnedInstallerChecksum -ChecksumPath $checksumPath -FileName 'install.ps1'
            $installerUrl = "https://raw.githubusercontent.com/microsoft/apm/v$approvedVersion/install.ps1"
            $installerPath = Join-Path ([IO.Path]::GetTempPath()) (
                'apm-install-{0}.ps1' -f [Guid]::NewGuid().ToString('N')
            )
            $previousSecurityProtocol = [Net.ServicePointManager]::SecurityProtocol
            $previousVersion = $env:VERSION
            try {
                [Net.ServicePointManager]::SecurityProtocol = $previousSecurityProtocol -bor
                    [Net.SecurityProtocolType]::Tls12
                Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath -UseBasicParsing
                $actualHash = (Get-FileHash -LiteralPath $installerPath -Algorithm SHA256).Hash
                if ($actualHash -ne $expectedHash) {
                    throw 'Downloaded install.ps1 does not match the pinned SHA256 checksum; refusing to execute it.'
                }
                $env:VERSION = "v$approvedVersion"
                & $installerPath
            }
            finally {
                $env:VERSION = $previousVersion
                [Net.ServicePointManager]::SecurityProtocol = $previousSecurityProtocol
                Remove-Item -LiteralPath $installerPath -Force -ErrorAction SilentlyContinue
            }
            Update-ProcessPath
            $apmCommand = @(Get-Command -Name apm -CommandType Application -ErrorAction Stop)[0]
            $activeVersion = ConvertTo-ApmVersion -Text ((& $apmCommand.Source --version 2>&1) -join "`n")
            if ($activeVersion -ne $approvedVersion) {
                throw "APM installation completed but version $approvedVersion is not active."
            }
        }
        if ($null -eq $apmCommand) {
            throw 'Required command is not available on PATH: apm'
        }

        $timestamp = [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')
        $backupBase = Join-Path -Path $globalApmDirectory -ChildPath "backups/$($script:BackupNamespace)"
        $backupDirectory = Join-Path -Path $backupBase -ChildPath $timestamp
        $counter = 0
        while (Test-Path -LiteralPath $backupDirectory) {
            $counter++
            $backupDirectory = Join-Path -Path $backupBase -ChildPath "${timestamp}-$counter"
        }
        $snapshotRoot = Join-Path $backupDirectory 'snapshot'
        $inventoryPath = Join-Path $backupDirectory 'inventory.tsv'
        $absentPath = Join-Path $backupDirectory 'originally-absent.txt'
        $stagingRoot = Join-Path $backupDirectory 'staging'
        $null = New-Item -ItemType Directory -Path $snapshotRoot -Force
        $null = New-Item -ItemType Directory -Path $stagingRoot -Force
        Set-Content -LiteralPath $inventoryPath -Value @() -Encoding UTF8
        Set-Content -LiteralPath $absentPath -Value @() -Encoding UTF8

        $relativePaths = @(
            '.apm/apm.yml'
            '.apm/apm.lock.yaml'
            '.apm/.apm'
            '.apm/apm_modules'
            '.apm/config.json'
            '.codex/AGENTS.md'
            '.codex/config.toml'
            '.copilot/copilot-instructions.md'
            '.copilot/mcp-config.json'
        )
        foreach ($skillName in $script:ManagedSkills) {
            $relativePaths += ".agents/skills/$skillName"
        }
        foreach ($relativePath in $relativePaths) {
            Save-GlobalSnapshotPath -HomePath $HomePath -RelativePath $relativePath `
                -SnapshotRoot $snapshotRoot -InventoryPath $inventoryPath -AbsentPath $absentPath
        }

        Copy-ManagedPath -Source $manifestPath -Destination (Join-Path $stagingRoot 'apm.yml')
        Copy-ManagedPath -Source $lockfilePath -Destination (Join-Path $stagingRoot 'apm.lock.yaml')
        Copy-ManagedPath -Source $sourceApmPath -Destination (Join-Path $stagingRoot '.apm')
        if ((Get-FileHash -LiteralPath $manifestPath).Hash -cne
            (Get-FileHash -LiteralPath (Join-Path $stagingRoot 'apm.yml')).Hash) {
            throw 'Staged APM manifest verification failed.'
        }
        if ((Get-FileHash -LiteralPath $lockfilePath).Hash -cne
            (Get-FileHash -LiteralPath (Join-Path $stagingRoot 'apm.lock.yaml')).Hash) {
            throw 'Staged APM lockfile verification failed.'
        }
        if (-not (Test-DirectoryContentEqual -ReferencePath $sourceApmPath `
                -DifferencePath (Join-Path $stagingRoot '.apm'))) {
            throw 'Staged local APM source verification failed.'
        }

        $mutationStarted = $false
        try {
            $mutationStarted = $true
            Set-ManagedPath -Source (Join-Path $stagingRoot 'apm.yml') `
                -Destination (Join-Path $globalApmDirectory 'apm.yml') -Confirm:$false
            Set-ManagedPath -Source (Join-Path $stagingRoot 'apm.lock.yaml') `
                -Destination (Join-Path $globalApmDirectory 'apm.lock.yaml') -Confirm:$false
            Set-ManagedPath -Source (Join-Path $stagingRoot '.apm') `
                -Destination (Join-Path $globalApmDirectory '.apm') -Confirm:$false

            Remove-ManagedPath -Path (Join-Path $codexDirectory 'AGENTS.md') -Confirm:$false
            Remove-ManagedPath -Path (Join-Path $copilotDirectory 'copilot-instructions.md') -Confirm:$false
            foreach ($skillName in $script:ManagedSkills) {
                Remove-ManagedPath -Path (Join-Path $agentsDirectory "skills/$skillName") -Confirm:$false
            }

            if ($codexMcpRemove) {
                Invoke-ExternalCommand -Executable $codexCommand.Source `
                    -ArgumentList @('mcp', 'remove', $script:GithubMcpName)
            }
            if ($copilotMcpRemove) {
                Set-ManagedPath -Source $cleanedCopilotConfigPath -Destination $copilotConfigPath `
                    -Confirm:$false
            }

            Invoke-ExternalCommand -Executable $apmCommand.Source `
                -ArgumentList @('install', '--global', '--frozen')

            $savedErrorActionPreference = $ErrorActionPreference
            try {
                $ErrorActionPreference = 'Continue'
                & $codexCommand.Source mcp get $script:GithubMcpName --json `
                    1> (Join-Path $preflightDirectory 'github-mcp-after.json') `
                    2> (Join-Path $preflightDirectory 'github-mcp-after.err')
                $mcpAfterExitCode = $LASTEXITCODE
            }
            finally {
                $ErrorActionPreference = $savedErrorActionPreference
            }
            if ($mcpAfterExitCode -eq 0) {
                throw "GitHub MCP entry '$($script:GithubMcpName)' remains in Codex after deployment."
            }
            $mcpAfterError = Get-Content `
                -LiteralPath (Join-Path $preflightDirectory 'github-mcp-after.err') -Raw
            $expectedAfterError = "No MCP server named '$($script:GithubMcpName)' found."
            if ($mcpAfterError.IndexOf($expectedAfterError, [StringComparison]::Ordinal) -lt 0) {
                throw "Unable to verify removal of the Codex MCP entry '$($script:GithubMcpName)'."
            }
            if ($copilotMcpRemove) {
                $copilotAfter = [System.IO.File]::ReadAllText($copilotConfigPath) | ConvertFrom-Json
                $serversAfter = $copilotAfter.PSObject.Properties['mcpServers'].Value
                if ($null -ne $serversAfter.PSObject.Properties[$script:GithubMcpName]) {
                    throw "GitHub MCP entry '$($script:GithubMcpName)' remains in Copilot after deployment."
                }
            }

            foreach ($skillName in $script:LocalSkills) {
                Set-ManagedPath -Source (Join-Path $globalApmDirectory ".apm/skills/$skillName") `
                    -Destination (Join-Path $agentsDirectory "skills/$skillName") -Confirm:$false
            }

            Invoke-ExternalCommand -Executable $apmCommand.Source -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'codex', '--single-agents',
                    '--output', (Join-Path $codexDirectory 'AGENTS.md'), '--dry-run'
                )
            Invoke-ExternalCommand -Executable $apmCommand.Source -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'copilot', '--single-agents',
                    '--output', (Join-Path $copilotDirectory 'copilot-instructions.md'), '--dry-run'
                )
            Invoke-ExternalCommand -Executable $apmCommand.Source -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'codex', '--single-agents',
                    '--output', (Join-Path $codexDirectory 'AGENTS.md')
                )
            Invoke-ExternalCommand -Executable $apmCommand.Source -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'copilot', '--single-agents',
                    '--output', (Join-Path $copilotDirectory 'copilot-instructions.md')
                )

            if ((Get-FileHash -LiteralPath $manifestPath).Hash -cne
                (Get-FileHash -LiteralPath (Join-Path $globalApmDirectory 'apm.yml')).Hash) {
                throw 'Deployed APM manifest differs from the reviewed source.'
            }
            if (-not (Test-LockfileContentEqual -ReferencePath $lockfilePath `
                    -DifferencePath (Join-Path $globalApmDirectory 'apm.lock.yaml'))) {
                throw 'Deployed APM lockfile differs from the reviewed source.'
            }
            if (-not (Test-DirectoryContentEqual -ReferencePath $sourceApmPath `
                    -DifferencePath (Join-Path $globalApmDirectory '.apm'))) {
                throw 'Deployed local APM sources differ from the reviewed source.'
            }
            foreach ($skillName in $script:LocalSkills) {
                if (-not (Test-DirectoryContentEqual `
                        -ReferencePath (Join-Path $sourceApmPath "skills/$skillName") `
                        -DifferencePath (Join-Path $agentsDirectory "skills/$skillName"))) {
                    throw "Deployed local skill differs from its reviewed source: $skillName"
                }
            }
            foreach ($skillName in $script:ManagedSkills) {
                if (-not (Test-Path -LiteralPath (Join-Path $agentsDirectory "skills/$skillName") `
                        -PathType Container)) {
                    throw "Managed skill was not deployed: $skillName"
                }
            }
            if (-not (Test-ApmGeneratedFile -Path (Join-Path $codexDirectory 'AGENTS.md'))) {
                throw 'Codex instructions do not contain the expected APM marker.'
            }
            if (-not (Test-ApmGeneratedFile -Path (Join-Path $copilotDirectory 'copilot-instructions.md'))) {
                throw 'Copilot instructions do not contain the expected APM marker.'
            }
            $projectDocSettingAfter = @(
                Get-ProjectDocSetting -Path (Join-Path $codexDirectory 'config.toml')
            ) -join "`n"
            if ($projectDocSettingBefore -cne $projectDocSettingAfter) {
                throw 'Codex project_doc_max_bytes changed during deployment.'
            }

            $mutationStarted = $false
            Write-Information -MessageData 'Global APM configuration is ready.' -InformationAction Continue
            Write-Information -MessageData "Rollback snapshot retained at: $backupDirectory" `
                -InformationAction Continue
            Write-Information -MessageData 'Start new Codex and Copilot sessions to load the configuration.' `
                -InformationAction Continue
        }
        catch {
            $deploymentError = $_
            if ($mutationStarted) {
                Write-Warning "Deployment failed; restoring snapshot: $backupDirectory"
                try {
                    Restore-GlobalSnapshot -HomePath $HomePath -SnapshotRoot $snapshotRoot `
                        -InventoryPath $inventoryPath
                    Write-Warning "Rollback completed successfully. Snapshot retained at: $backupDirectory"
                }
                catch {
                    Write-Warning "Rollback encountered errors. Preserve and inspect: $backupDirectory"
                    Write-Warning $_.Exception.Message
                }
            }
            throw $deploymentError
        }
    }
    finally {
        if ([System.IO.Directory]::Exists($preflightDirectory)) {
            [System.IO.Directory]::Delete($preflightDirectory, $true)
        }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) {
        throw 'Bootstrap-Global.ps1 supports Windows; use bootstrap-global.sh on Linux.'
    }
    $repositoryRoot = Split-Path -Parent $PSScriptRoot
    $homePath = $HOME
    if ([string]::IsNullOrWhiteSpace($homePath)) {
        throw 'HOME must be set.'
    }

    $invokeParameters = @{
        HomePath = $homePath
        RepositoryRoot = $repositoryRoot
        WhatIf = [bool]$WhatIfPreference
    }
    $explicitConfirmParameter = Get-ExplicitConfirmParameter -BoundParameters $PSBoundParameters
    foreach ($key in $explicitConfirmParameter.Keys) {
        $invokeParameters[$key] = $explicitConfirmParameter[$key]
    }
    Invoke-GlobalBootstrap @invokeParameters
}
