<#
.SYNOPSIS
Installs this repository's APM baseline at user scope.

.DESCRIPTION
Copies apm.yml into the current user's APM directory, installs or updates the
global dependencies, compiles complete instruction files for Codex and GitHub
Copilot, and sets Codex's project documentation byte limit. Existing
hand-authored instruction files are moved to timestamped backup paths. APM-
generated instruction files are replaced in place.

.PARAMETER Update
Refreshes the global dependency resolutions with apm update before compiling
the instruction files.

.EXAMPLE
./scripts/Bootstrap-Global.ps1

Installs the current global baseline.

.EXAMPLE
./scripts/Bootstrap-Global.ps1 -Update

Refreshes global dependencies and regenerates both instruction files.

.OUTPUTS
None. The script writes status information to the host.

.NOTES
The script never reads, writes, or displays GITHUB_TOKEN. Provide it separately
in the runtime environment when using the GitHub MCP server. The implementation
supports Windows PowerShell 5.1 and PowerShell 7.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param(
    [Parameter()]
    [switch]$Update
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$script:GeneratedMarker = '<!-- Generated by APM CLI from .apm/ primitives -->'
$script:ProjectDocMaxBytes = 131072

function Test-ApmGeneratedFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not [System.IO.File]::Exists($Path)) {
        return $false
    }

    $item = Get-Item -LiteralPath $Path -Force
    if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        return $false
    }

    $lineNumber = 0
    foreach ($line in [System.IO.File]::ReadLines($Path)) {
        $lineNumber++
        if ($line -ceq $script:GeneratedMarker) {
            return $true
        }
        if ($lineNumber -ge 6) {
            break
        }
    }

    return $false
}

function Save-HandAuthoredInstructionFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [string]$Timestamp
    )

    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) {
        return
    }

    if (Test-ApmGeneratedFile -Path $Path) {
        return
    }

    $backupPath = '{0}.backup-{1}' -f $Path, $Timestamp
    $counter = 0
    while (Test-Path -LiteralPath $backupPath) {
        $counter++
        $backupPath = '{0}.backup-{1}.{2}' -f $Path, $Timestamp, $counter
    }

    Move-Item -LiteralPath $Path -Destination $backupPath
    Write-Information -MessageData "Backed up hand-authored file: $backupPath" -InformationAction Continue
}

function Set-CodexProjectDocLimit {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not $PSCmdlet.ShouldProcess($Path, 'Set Codex project documentation byte limit')) {
        return
    }

    $directory = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $directory -Force
    }

    if (Test-Path -LiteralPath $Path) {
        $item = Get-Item -LiteralPath $Path -Force
        if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "Refusing to replace symlinked Codex configuration: $Path"
        }
        if ($item.PSIsContainer) {
            throw "Codex configuration is not a regular file: $Path"
        }
        $sourceLines = [System.IO.File]::ReadAllLines($Path)
    }
    else {
        $sourceLines = @()
    }

    $outputLines = [System.Collections.Generic.List[string]]::new()
    $inTopLevel = $true
    $wroteSetting = $false

    foreach ($line in $sourceLines) {
        if ($inTopLevel -and $line -match '^\s*\[') {
            if (-not $wroteSetting) {
                $outputLines.Add("project_doc_max_bytes = $script:ProjectDocMaxBytes")
                $outputLines.Add('')
                $wroteSetting = $true
            }
            $inTopLevel = $false
        }

        if ($inTopLevel -and $line -match '^\s*project_doc_max_bytes\s*=') {
            if (-not $wroteSetting) {
                $outputLines.Add("project_doc_max_bytes = $script:ProjectDocMaxBytes")
                $wroteSetting = $true
            }
            continue
        }

        $outputLines.Add($line)
    }

    if (-not $wroteSetting) {
        $outputLines.Add("project_doc_max_bytes = $script:ProjectDocMaxBytes")
    }

    $temporaryPath = '{0}.tmp.{1}' -f $Path, [Guid]::NewGuid().ToString('N')
    $replacementBackupPath = '{0}.replace-backup.{1}' -f $Path, [Guid]::NewGuid().ToString('N')
    $encoding = [System.Text.UTF8Encoding]::new($false)
    try {
        [System.IO.File]::WriteAllLines($temporaryPath, $outputLines, $encoding)
        if ([System.IO.File]::Exists($Path)) {
            [System.IO.File]::Replace($temporaryPath, $Path, $replacementBackupPath)
            Remove-Item -LiteralPath $replacementBackupPath -Force
        }
        else {
            Move-Item -LiteralPath $temporaryPath -Destination $Path
        }
    }
    finally {
        if ([System.IO.File]::Exists($temporaryPath)) {
            Remove-Item -LiteralPath $temporaryPath -Force
        }
        if ([System.IO.File]::Exists($replacementBackupPath)) {
            Remove-Item -LiteralPath $replacementBackupPath -Force
        }
    }
}

function Invoke-ApmCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Executable,

        [Parameter(Mandatory)]
        [string[]]$ArgumentList
    )

    & $Executable @ArgumentList
    if ($LASTEXITCODE -ne 0) {
        $renderedArguments = $ArgumentList -join ' '
        throw "APM command failed with exit code ${LASTEXITCODE}: apm $renderedArguments"
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    $apmCommands = @(Get-Command -Name apm -CommandType Application -ErrorAction SilentlyContinue)
    if ($apmCommands.Count -eq 0) {
        throw 'APM CLI is not available on PATH.'
    }
    $apmCommand = $apmCommands[0]

    $repoRoot = Split-Path -Parent $PSScriptRoot
    $manifestPath = Join-Path -Path $repoRoot -ChildPath 'apm.yml'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "APM manifest not found: $manifestPath"
    }

    $homePath = $HOME
    if ([string]::IsNullOrWhiteSpace($homePath)) {
        throw 'HOME must be set.'
    }

    $globalApmDirectory = Join-Path -Path $homePath -ChildPath '.apm'
    $codexDirectory = Join-Path -Path $homePath -ChildPath '.codex'
    $copilotDirectory = Join-Path -Path $homePath -ChildPath '.copilot'
    $timestamp = [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss')
    $operation = if ($Update.IsPresent) {
        'Update global APM dependencies and regenerate user instructions'
    }
    else {
        'Install global APM dependencies and generate user instructions'
    }

    Invoke-ApmCommand -Executable $apmCommand.Source -ArgumentList @('--version')

    if ($PSCmdlet.ShouldProcess($homePath, $operation)) {
        foreach ($directory in @($globalApmDirectory, $codexDirectory, $copilotDirectory)) {
            if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
                $null = New-Item -ItemType Directory -Path $directory -Force
            }
        }

        $globalManifestPath = Join-Path $globalApmDirectory 'apm.yml'
        $existingGlobalManifest = Get-Item -LiteralPath $globalManifestPath -Force -ErrorAction SilentlyContinue
        if ($null -ne $existingGlobalManifest -and
            ($existingGlobalManifest.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "Refusing to replace symlinked global APM manifest: $globalManifestPath"
        }

        Save-HandAuthoredInstructionFile -Path (Join-Path $codexDirectory 'AGENTS.md') -Timestamp $timestamp
        Save-HandAuthoredInstructionFile -Path (Join-Path $copilotDirectory 'copilot-instructions.md') -Timestamp $timestamp
        Save-HandAuthoredInstructionFile -Path (Join-Path $copilotDirectory 'AGENTS.md') -Timestamp $timestamp

        Copy-Item -LiteralPath $manifestPath -Destination $globalManifestPath -Force
        Set-CodexProjectDocLimit -Path (Join-Path $codexDirectory 'config.toml')

        if ($Update.IsPresent) {
            Invoke-ApmCommand -Executable $apmCommand.Source -ArgumentList @('update', '--global', '--yes')
        }
        else {
            Invoke-ApmCommand -Executable $apmCommand.Source -ArgumentList @('install', '--global')
        }

        Push-Location -LiteralPath $globalApmDirectory
        try {
            Invoke-ApmCommand -Executable $apmCommand.Source -ArgumentList @(
                'compile', '--target', 'codex', '--single-agents',
                '--output', (Join-Path $codexDirectory 'AGENTS.md')
            )
            Invoke-ApmCommand -Executable $apmCommand.Source -ArgumentList @(
                'compile', '--target', 'copilot', '--single-agents',
                '--output', (Join-Path $copilotDirectory 'copilot-instructions.md')
            )
        }
        finally {
            Pop-Location
        }

        Write-Information -MessageData 'Global APM configuration is ready.' -InformationAction Continue
        Write-Information -MessageData 'Set GITHUB_TOKEN in your runtime environment to use the GitHub MCP server.' -InformationAction Continue
        Write-Information -MessageData 'Start new Codex and Copilot sessions to load the updated configuration.' -InformationAction Continue
    }
}
