#!/usr/bin/env bash

set -euo pipefail

readonly GENERATED_MARKER='<!-- Generated by APM CLI from .apm/ primitives -->'
readonly GITHUB_MCP_NAME='github-mcp-server'
readonly GITHUB_MCP_URL='https://api.githubcopilot.com/mcp/'
readonly BACKUP_NAMESPACE='agent-engineering-baseline'

readonly LOCAL_SKILLS=(
    a11y
    agent-safety
    ansible
    powershell-module-engineering
)

readonly MANAGED_SKILLS=(
    a11y
    agent-safety
    ansible
    powershell-module-engineering
    code-simplification
    dependabot
    git-commit
    github-actions-hardening
    msgraph
)

usage() {
    cat <<'EOF'
Usage: scripts/bootstrap-global.sh [--dry-run]

Deploy this repository's reviewed APM manifest, lockfile, local sources,
skills, MCP configuration, and generated instructions at user scope.

Options:
  --dry-run  Run preflight checks and describe the deployment without changing
             the user profile.
  -h, --help Show this help text.
EOF
}

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command is not available on PATH: $1"
}

assert_regular_file() {
    local path=$1
    local label=$2

    [ ! -L "$path" ] || die "$label is a symbolic link: $path"
    [ -f "$path" ] || die "$label is not a regular file: $path"
}

assert_directory_without_links() {
    local path=$1
    local label=$2
    local linked_path

    [ ! -L "$path" ] || die "$label is a symbolic link: $path"
    [ -d "$path" ] || die "$label is not a directory: $path"
    linked_path=$(find "$path" -type l -print -quit)
    [ -z "$linked_path" ] || die "$label contains a symbolic link: $linked_path"
}

assert_safe_existing_target() {
    local path=$1
    local expected_type=${2-}
    local linked_path

    if [ -L "$path" ]; then
        die "Refusing to manage symbolic-link target: $path"
    fi

    if [ ! -e "$path" ]; then
        return
    fi

    case "$expected_type" in
        file)
            [ -f "$path" ] || die "Managed target is not a regular file: $path"
            ;;
        directory)
            [ -d "$path" ] || die "Managed target is not a directory: $path"
            ;;
        tree)
            [ -d "$path" ] || die "Managed target is not a directory: $path"
            linked_path=$(find "$path" -type l -print -quit)
            [ -z "$linked_path" ] || die "Managed target contains a symbolic link: $linked_path"
            ;;
    esac
}

is_apm_generated() {
    local path=$1

    [ ! -L "$path" ] || return 1
    [ -f "$path" ] || return 1

    awk -v marker="$GENERATED_MARKER" '
        NR <= 6 && $0 == marker { found = 1 }
        END { exit(found ? 0 : 1) }
    ' "$path"
}

extract_project_doc_setting() {
    local path=$1
    local output_path=$2

    : > "$output_path"
    [ -f "$path" ] || return 0
    awk '
        /^[[:space:]]*\[/ { exit }
        /^[[:space:]]*project_doc_max_bytes[[:space:]]*=/ { print }
    ' "$path" > "$output_path"
}

verify_default_github_mcp() {
    local json_path=$1

    jq -e --arg name "$GITHUB_MCP_NAME" --arg url "$GITHUB_MCP_URL" '
        . == {
            name: $name,
            enabled: true,
            disabled_reason: null,
            transport: {
                type: "streamable_http",
                url: $url,
                bearer_token_env_var: "GITHUB_TOKEN",
                http_headers: null,
                env_http_headers: null,
                http_headers_helper: null
            },
            enabled_tools: null,
            disabled_tools: null,
            startup_timeout_sec: null,
            tool_timeout_sec: null
        }
    ' "$json_path" >/dev/null
}

copy_path() {
    local source_path=$1
    local destination_path=$2

    mkdir -p "$(dirname "$destination_path")"
    cp -a -- "$source_path" "$destination_path"
}

remove_path() {
    local path=$1

    if [ -e "$path" ] || [ -L "$path" ]; then
        rm -rf -- "$path"
    fi
}

replace_path() {
    local source_path=$1
    local destination_path=$2
    local staged_path="${destination_path}.agent-baseline-stage-$$"

    if [ -e "$staged_path" ] || [ -L "$staged_path" ]; then
        die "Temporary replacement path already exists: $staged_path"
    fi
    mkdir -p "$(dirname "$destination_path")"
    copy_path "$source_path" "$staged_path"
    remove_path "$destination_path"
    mv -- "$staged_path" "$destination_path"
}

snapshot_path() {
    local relative_path=$1
    local source_path="$home_path/$relative_path"
    local snapshot_path="$snapshot_root/$relative_path"

    if [ -e "$source_path" ] || [ -L "$source_path" ]; then
        printf 'present\t%s\n' "$relative_path" >> "$inventory_path"
        copy_path "$source_path" "$snapshot_path"
    else
        printf 'absent\t%s\n' "$relative_path" >> "$inventory_path"
        printf '%s\n' "$relative_path" >> "$absent_path"
    fi
}

restore_snapshot() {
    local status
    local relative_path
    local destination_path
    local snapshot_path
    local restore_failed=false

    [ -n "${inventory_path-}" ] && [ -f "$inventory_path" ] || return 0

    while IFS=$'\t' read -r status relative_path; do
        [ -n "$relative_path" ] || continue
        destination_path="$home_path/$relative_path"
        snapshot_path="$snapshot_root/$relative_path"

        if ! remove_path "$destination_path"; then
            restore_failed=true
            continue
        fi
        if [ "$status" = present ] && ! copy_path "$snapshot_path" "$destination_path"; then
            restore_failed=true
        fi
    done < "$inventory_path"

    [ "$restore_failed" = false ]
}

on_exit() {
    local exit_code=$?

    trap - EXIT HUP INT TERM
    if [ -n "${preflight_temp-}" ] && [ -d "$preflight_temp" ]; then
        rm -rf -- "$preflight_temp"
    fi

    if [ "$exit_code" -ne 0 ] && [ "${mutation_started-false}" = true ]; then
        printf 'Deployment failed; restoring snapshot: %s\n' "$backup_dir" >&2
        if restore_snapshot; then
            printf 'Rollback completed successfully. Snapshot retained at: %s\n' "$backup_dir" >&2
        else
            printf 'Rollback encountered errors. Preserve and inspect: %s\n' "$backup_dir" >&2
        fi
    fi

    exit "$exit_code"
}

dry_run=false
while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            [ "$dry_run" = false ] || die '--dry-run may be specified only once.'
            dry_run=true
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
    shift
done

for command_name in apm codex awk cmp cp date diff dirname find grep mkdir mktemp mv rm; do
    require_command "$command_name"
done

script_dir=$(CDPATH='' cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
repo_root=$(CDPATH='' cd -- "$script_dir/.." && pwd -P)
manifest_path="$repo_root/apm.yml"
lockfile_path="$repo_root/apm.lock.yaml"
source_apm_path="$repo_root/.apm"
home_path=${HOME:?HOME must be set.}

[ ! -L "$home_path" ] || die "HOME must not be a symbolic link: $home_path"
[ -d "$home_path" ] || die "HOME is not a directory: $home_path"
assert_regular_file "$manifest_path" 'Repository APM manifest'
assert_regular_file "$lockfile_path" 'Repository APM lockfile'
assert_directory_without_links "$source_apm_path" 'Repository local APM source'

for skill_name in "${LOCAL_SKILLS[@]}"; do
    skill_source="$source_apm_path/skills/$skill_name"
    assert_directory_without_links "$skill_source" "Local skill source '$skill_name'"
    assert_regular_file "$skill_source/SKILL.md" "Local skill entrypoint '$skill_name'"
done

global_apm_dir="$home_path/.apm"
codex_dir="$home_path/.codex"
copilot_dir="$home_path/.copilot"
agents_dir="$home_path/.agents"

assert_safe_existing_target "$global_apm_dir" directory
assert_safe_existing_target "$codex_dir" directory
assert_safe_existing_target "$copilot_dir" directory
assert_safe_existing_target "$agents_dir" directory
assert_safe_existing_target "$agents_dir/skills" directory
assert_safe_existing_target "$global_apm_dir/backups" directory
assert_safe_existing_target "$global_apm_dir/apm.yml" file
assert_safe_existing_target "$global_apm_dir/apm.lock.yaml" file
assert_safe_existing_target "$global_apm_dir/.apm" tree
assert_safe_existing_target "$global_apm_dir/apm_modules" tree
assert_safe_existing_target "$global_apm_dir/config.json" file
assert_safe_existing_target "$codex_dir/AGENTS.md" file
assert_safe_existing_target "$codex_dir/config.toml" file
assert_safe_existing_target "$copilot_dir/copilot-instructions.md" file
assert_safe_existing_target "$copilot_dir/mcp-config.json" file
for skill_name in "${MANAGED_SKILLS[@]}"; do
    assert_safe_existing_target "$agents_dir/skills/$skill_name" tree
done

preflight_temp=$(mktemp -d "${TMPDIR:-/tmp}/agent-baseline-preflight.XXXXXX")
mutation_started=false
trap on_exit EXIT HUP INT TERM

mcp_recycle=false
if codex mcp get "$GITHUB_MCP_NAME" --json > "$preflight_temp/github-mcp.json" 2> "$preflight_temp/github-mcp.err"; then
    require_command jq
    if ! verify_default_github_mcp "$preflight_temp/github-mcp.json"; then
        die "Existing Codex MCP entry '$GITHUB_MCP_NAME' is customized; refusing to replace it."
    fi
    mcp_recycle=true
else
    if ! grep -F "No MCP server named '$GITHUB_MCP_NAME' found." "$preflight_temp/github-mcp.err" >/dev/null; then
        die "Unable to inspect the existing Codex MCP entry '$GITHUB_MCP_NAME'."
    fi
fi

extract_project_doc_setting "$codex_dir/config.toml" "$preflight_temp/project-doc-setting.before"

if [ "$dry_run" = true ]; then
    printf '%s\n' 'Dry run: preflight checks passed; no user-profile files were changed.'
    printf '%s\n' 'Dry run: would copy the reviewed manifest, lockfile, and local .apm sources.'
    printf '%s\n' 'Dry run: would run apm install --global --frozen and compile Codex/Copilot instructions.'
    if [ "$mcp_recycle" = true ]; then
        printf "Dry run: would recycle the exact APM-owned Codex MCP entry '%s'.\n" "$GITHUB_MCP_NAME"
    fi
    exit 0
fi

timestamp=$(date -u '+%Y%m%dT%H%M%SZ')
backup_base="$global_apm_dir/backups/$BACKUP_NAMESPACE"
backup_dir="$backup_base/$timestamp"
counter=0
while [ -e "$backup_dir" ] || [ -L "$backup_dir" ]; do
    counter=$((counter + 1))
    backup_dir="$backup_base/${timestamp}-$counter"
done
snapshot_root="$backup_dir/snapshot"
inventory_path="$backup_dir/inventory.tsv"
absent_path="$backup_dir/originally-absent.txt"
staging_root="$backup_dir/staging"

mkdir -p "$snapshot_root" "$staging_root"
: > "$inventory_path"
: > "$absent_path"

managed_paths=(
    '.apm/apm.yml'
    '.apm/apm.lock.yaml'
    '.apm/.apm'
    '.apm/apm_modules'
    '.apm/config.json'
    '.codex/AGENTS.md'
    '.codex/config.toml'
    '.copilot/copilot-instructions.md'
    '.copilot/mcp-config.json'
)
for skill_name in "${MANAGED_SKILLS[@]}"; do
    managed_paths+=(".agents/skills/$skill_name")
done
for relative_path in "${managed_paths[@]}"; do
    snapshot_path "$relative_path"
done

copy_path "$manifest_path" "$staging_root/apm.yml"
copy_path "$lockfile_path" "$staging_root/apm.lock.yaml"
copy_path "$source_apm_path" "$staging_root/.apm"
cmp -s "$manifest_path" "$staging_root/apm.yml" || die 'Staged APM manifest verification failed.'
cmp -s "$lockfile_path" "$staging_root/apm.lock.yaml" || die 'Staged APM lockfile verification failed.'
diff -qr "$source_apm_path" "$staging_root/.apm" >/dev/null || die 'Staged local APM source verification failed.'

mutation_started=true
replace_path "$staging_root/apm.yml" "$global_apm_dir/apm.yml"
replace_path "$staging_root/apm.lock.yaml" "$global_apm_dir/apm.lock.yaml"
replace_path "$staging_root/.apm" "$global_apm_dir/.apm"

remove_path "$codex_dir/AGENTS.md"
remove_path "$copilot_dir/copilot-instructions.md"
for skill_name in "${MANAGED_SKILLS[@]}"; do
    remove_path "$agents_dir/skills/$skill_name"
done

if [ "$mcp_recycle" = true ]; then
    codex mcp remove "$GITHUB_MCP_NAME"
fi

apm install --global --frozen

for skill_name in "${LOCAL_SKILLS[@]}"; do
    replace_path "$global_apm_dir/.apm/skills/$skill_name" "$agents_dir/skills/$skill_name"
done

(
    cd "$global_apm_dir"
    apm compile --target codex --single-agents --output "$codex_dir/AGENTS.md" --dry-run
    apm compile --target copilot --single-agents --output "$copilot_dir/copilot-instructions.md" --dry-run
    apm compile --target codex --single-agents --output "$codex_dir/AGENTS.md"
    apm compile --target copilot --single-agents --output "$copilot_dir/copilot-instructions.md"
)

cmp -s "$manifest_path" "$global_apm_dir/apm.yml" || die 'Deployed APM manifest differs from the reviewed source.'
diff -I '^generated_at:' "$lockfile_path" "$global_apm_dir/apm.lock.yaml" >/dev/null ||
    die 'Deployed APM lockfile differs from the reviewed source.'
diff -qr "$source_apm_path" "$global_apm_dir/.apm" >/dev/null ||
    die 'Deployed local APM sources differ from the reviewed source.'

for skill_name in "${LOCAL_SKILLS[@]}"; do
    diff -qr "$source_apm_path/skills/$skill_name" "$agents_dir/skills/$skill_name" >/dev/null ||
        die "Deployed local skill differs from its reviewed source: $skill_name"
done
for skill_name in "${MANAGED_SKILLS[@]}"; do
    [ -d "$agents_dir/skills/$skill_name" ] || die "Managed skill was not deployed: $skill_name"
done

is_apm_generated "$codex_dir/AGENTS.md" || die 'Codex instructions do not contain the expected APM marker.'
is_apm_generated "$copilot_dir/copilot-instructions.md" ||
    die 'Copilot instructions do not contain the expected APM marker.'
extract_project_doc_setting "$codex_dir/config.toml" "$preflight_temp/project-doc-setting.after"
cmp -s "$preflight_temp/project-doc-setting.before" "$preflight_temp/project-doc-setting.after" ||
    die 'Codex project_doc_max_bytes changed during deployment.'

mutation_started=false
printf '%s\n' 'Global APM configuration is ready.'
printf 'Rollback snapshot retained at: %s\n' "$backup_dir"
printf '%s\n' 'Set GITHUB_TOKEN in your runtime environment to use the GitHub MCP server.'
printf '%s\n' 'Start new Codex and Copilot sessions to load the updated configuration.'
