<#
.SYNOPSIS
Installs and transactionally deploys the reviewed global APM baseline.

.DESCRIPTION
Installs the repository-pinned APM CLI when needed, preflights the
reviewed manifest, lockfile, local sources, and managed destinations, creates a
complete timestamped rollback snapshot, runs a frozen global installation,
deploys the local skills, and compiles Codex and Copilot instructions through
dry-run validation before writing them.

Any failure after profile mutation begins restores the snapshot automatically.
Successful snapshots are retained for manual rollback.

.EXAMPLE
./scripts/Bootstrap-Global.ps1

Deploys the reviewed global baseline.

.EXAMPLE
./scripts/Bootstrap-Global.ps1 -WhatIf

Runs preflight checks and describes the deployment without changing the user
profile.

.OUTPUTS
None. The script writes deployment status to the information stream.

.NOTES
The script supports Windows PowerShell 5.1 and PowerShell 7. It does not manage
Codex or Copilot configuration files or ~/.copilot/AGENTS.md.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param()

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$script:GeneratedMarker = '<!-- Generated by APM CLI from .apm/ primitives -->'
$script:BackupNamespace = 'agent-engineering-baseline'
$script:LocalSkills = @(
    'a11y'
    'agent-safety'
    'ansible'
    'powershell-pester-6'
    'powershell-module-engineering'
)
$script:ManagedSkills = @(
    'a11y'
    'agent-safety'
    'ansible'
    'powershell-pester-6'
    'powershell-module-engineering'
    'code-simplification'
    'dependabot'
    'git-commit'
    'github-actions-hardening'
    'msgraph'
)

function Test-ReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.IO.FileSystemInfo]$Item
    )

    return (($Item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0)
}

function Test-PathWithoutReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [ValidateSet('File', 'Directory')]
        [string]$PathType,

        [Parameter()]
        [switch]$AllowMissing,

        [Parameter()]
        [switch]$Recurse
    )

    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) {
        if ($AllowMissing.IsPresent) {
            return $true
        }
        return $false
    }

    if (Test-ReparsePoint -Item $item) {
        return $false
    }

    if ($PathType -eq 'File') {
        return (-not $item.PSIsContainer)
    }
    if (-not $item.PSIsContainer) {
        return $false
    }

    if ($Recurse.IsPresent) {
        $linkedItem = Get-ChildItem -LiteralPath $Path -Force -Recurse `
            -Attributes ReparsePoint -ErrorAction Stop |
            Select-Object -First 1
        return ($null -eq $linkedItem)
    }
    return $true
}

function Assert-PathWithoutReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [ValidateSet('File', 'Directory')]
        [string]$PathType,

        [Parameter()]
        [switch]$AllowMissing,

        [Parameter()]
        [switch]$Recurse,

        [Parameter(Mandatory)]
        [string]$Description
    )

    if (-not (Test-PathWithoutReparsePoint -Path $Path -PathType $PathType `
            -AllowMissing:$AllowMissing -Recurse:$Recurse)) {
        throw "$Description is missing, has the wrong type, or contains a reparse point: $Path"
    }
}

function Test-ApmGeneratedFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-PathWithoutReparsePoint -Path $Path -PathType File -AllowMissing)) {
        return $false
    }
    if (-not [System.IO.File]::Exists($Path)) {
        return $false
    }

    $reader = [System.IO.File]::OpenText($Path)
    try {
        $lineNumber = 0
        while (-not $reader.EndOfStream -and $lineNumber -lt 6) {
            $line = $reader.ReadLine()
            $lineNumber++
            if ($line -ceq $script:GeneratedMarker) {
                return $true
            }
        }
        return $false
    }
    finally {
        $reader.Dispose()
    }
}

function ConvertTo-ApmVersion {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Text)

    $match = [regex]::Match($Text, '(?<!\d)(\d+\.\d+\.\d+)(?!\d)')
    if (-not $match.Success) { throw "Unable to parse APM version from: $Text" }
    return [version]$match.Groups[1].Value
}

function Get-PinnedChecksum {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ChecksumPath,
        [Parameter(Mandatory)][string]$FileName
    )

    if (-not (Test-Path -LiteralPath $ChecksumPath -PathType Leaf)) {
        throw "Missing APM checksums: $ChecksumPath"
    }
    $pattern = '^([0-9a-f]{64})  ' + [regex]::Escape($FileName) + '$'
    $checksumMatches = @()
    foreach ($line in @([System.IO.File]::ReadAllLines($ChecksumPath))) {
        $match = [regex]::Match($line, $pattern)
        if ($match.Success) { $checksumMatches += $match.Groups[1].Value }
    }
    if ($checksumMatches.Count -ne 1) {
        throw "Expected exactly one lowercase SHA256 checksum for $FileName in $ChecksumPath"
    }
    return $checksumMatches[0]
}

function Assert-PinnedFileChecksum {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$ChecksumPath,
        [Parameter(Mandatory)][string]$FileName
    )

    Assert-PathWithoutReparsePoint -Path $Path -PathType File -Description $FileName
    $expectedHash = Get-PinnedChecksum -ChecksumPath $ChecksumPath -FileName $FileName
    $actualHash = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actualHash -cne $expectedHash) {
        throw "$FileName does not match the pinned SHA256 checksum; refusing to execute downloaded code."
    }
}

function Get-ApmWindowsLayout {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][version]$Version
    )

    if (-not [string]::IsNullOrWhiteSpace($env:APM_INSTALL_DIR)) {
        $binDirectory = [System.IO.Path]::GetFullPath($env:APM_INSTALL_DIR.Trim().TrimEnd('\', '/'))
        $installRoot = Split-Path -Parent $binDirectory
        if ([string]::IsNullOrWhiteSpace($installRoot)) { $installRoot = $binDirectory }
    }
    else {
        if ([string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
            throw 'LOCALAPPDATA must be set when APM_INSTALL_DIR is not specified.'
        }
        $installRoot = Join-Path $env:LOCALAPPDATA 'Programs/apm'
        $binDirectory = Join-Path $installRoot 'bin'
    }
    $releaseTag = "v$Version"
    $releasesDirectory = Join-Path $installRoot 'releases'
    $releaseDirectory = Join-Path $releasesDirectory $releaseTag
    $currentDirectory = Join-Path $installRoot 'current'
    return [PSCustomObject]@{
        InstallRoot = $installRoot
        BinDirectory = $binDirectory
        ReleasesDirectory = $releasesDirectory
        ReleaseDirectory = $releaseDirectory
        CurrentDirectory = $currentDirectory
        CurrentExecutable = Join-Path $currentDirectory 'apm.exe'
        ShimPath = Join-Path $binDirectory 'apm.cmd'
    }
}

function Test-PathWithinDirectory {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Directory
    )

    $fullPath = [System.IO.Path]::GetFullPath($Path).TrimEnd('\', '/')
    $fullDirectory = [System.IO.Path]::GetFullPath($Directory).TrimEnd('\', '/')
    $prefix = $fullDirectory + [System.IO.Path]::DirectorySeparatorChar
    return $fullPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)
}

function Get-ReparseTargetPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.IO.FileSystemInfo]$Item
    )

    $targets = @($Item.Target)
    if ($targets.Count -ne 1 -or [string]::IsNullOrWhiteSpace([string]$targets[0])) {
        throw "Unable to inspect reparse target: $($Item.FullName)"
    }
    $target = [string]$targets[0]
    if ($target.StartsWith('\??\')) { $target = $target.Substring(4) }
    if ($target.StartsWith('\\?\')) { $target = $target.Substring(4) }
    if (-not [System.IO.Path]::IsPathRooted($target)) {
        $target = Join-Path (Split-Path -Parent $Item.FullName) $target
    }
    return [System.IO.Path]::GetFullPath($target)
}

function Assert-PathAncestorsWithoutReparsePoint {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Description
    )

    $currentPath = [System.IO.Path]::GetFullPath($Path)
    if (-not (Test-Path -LiteralPath $currentPath)) {
        $currentPath = Split-Path -Parent $currentPath
    }
    while (-not [string]::IsNullOrWhiteSpace($currentPath)) {
        $item = Get-Item -LiteralPath $currentPath -Force -ErrorAction SilentlyContinue
        if ($null -ne $item -and (Test-ReparsePoint -Item $item)) {
            throw "$Description has a reparse-point ancestor: $currentPath"
        }
        $parentPath = Split-Path -Parent $currentPath
        if ([string]::IsNullOrWhiteSpace($parentPath) -or $parentPath -ceq $currentPath) {
            break
        }
        $currentPath = $parentPath
    }
}

function Assert-ApmWindowsLayoutSafe {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][object]$Layout
    )

    foreach ($directory in @($Layout.InstallRoot, $Layout.BinDirectory, $Layout.ReleasesDirectory)) {
        Assert-PathAncestorsWithoutReparsePoint -Path $directory -Description 'APM CLI layout'
        Assert-PathWithoutReparsePoint -Path $directory -PathType Directory -AllowMissing `
            -Description 'APM CLI layout directory'
    }
    Assert-PathAncestorsWithoutReparsePoint -Path $Layout.ReleaseDirectory `
        -Description 'APM release directory'
    Assert-PathWithoutReparsePoint -Path $Layout.ReleaseDirectory -PathType Directory `
        -AllowMissing -Recurse -Description 'APM release directory'
    Assert-PathAncestorsWithoutReparsePoint -Path (Split-Path -Parent $Layout.ShimPath) `
        -Description 'APM command shim'
    Assert-PathWithoutReparsePoint -Path $Layout.ShimPath -PathType File -AllowMissing `
        -Description 'APM command shim'

    $currentItem = Get-Item -LiteralPath $Layout.CurrentDirectory -Force -ErrorAction SilentlyContinue
    if ($null -ne $currentItem) {
        if (-not $currentItem.PSIsContainer -or -not (Test-ReparsePoint -Item $currentItem)) {
            throw "Refusing to replace unsafe APM current path: $($Layout.CurrentDirectory)"
        }
        $targetPath = Get-ReparseTargetPath -Item $currentItem
        if (-not (Test-PathWithinDirectory -Path $targetPath -Directory $Layout.ReleasesDirectory)) {
            throw "APM current junction points outside the releases directory: $targetPath"
        }
        Assert-PathWithoutReparsePoint -Path $targetPath -PathType Directory -Recurse `
            -Description 'APM current release target'
    }
}

function Remove-ApmJunction {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param([Parameter(Mandatory)][string]$Path)

    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) { return }
    if (-not $item.PSIsContainer -or -not (Test-ReparsePoint -Item $item)) {
        throw "Refusing to remove non-junction APM path: $Path"
    }
    if ($PSCmdlet.ShouldProcess($Path, 'Remove APM junction')) {
        [System.IO.Directory]::Delete($Path)
    }
}

function ConvertTo-ApmCommandShimContent {
    [CmdletBinding()]
    param()

    return "@echo off`r`nREM Generated by the reviewed APM bootstrap -- do not hand-edit.`r`n`"%~dp0..\current\apm.exe`" %*`r`n"
}

function Set-ApmUserPath {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)][string]$CurrentDirectory,
        [Parameter(Mandatory)][string]$BinDirectory
    )

    $separator = [System.IO.Path]::PathSeparator
    $userEntries = @([Environment]::GetEnvironmentVariable('Path', 'User') -split [regex]::Escape($separator))
    $processEntries = @($env:PATH -split [regex]::Escape($separator))
    $preferred = @($CurrentDirectory, $BinDirectory)
    $newUserEntries = @($preferred)
    foreach ($entry in $userEntries) {
        if (-not [string]::IsNullOrWhiteSpace($entry) -and $preferred -notcontains $entry) {
            $newUserEntries += $entry
        }
    }
    $newProcessEntries = @($preferred)
    foreach ($entry in $processEntries) {
        if (-not [string]::IsNullOrWhiteSpace($entry) -and $preferred -notcontains $entry) {
            $newProcessEntries += $entry
        }
    }
    if ($PSCmdlet.ShouldProcess('user and process PATH', 'Add APM command directories')) {
        [Environment]::SetEnvironmentVariable('Path', ($newUserEntries -join $separator), 'User')
        $env:PATH = $newProcessEntries -join $separator
    }
}

function Install-PinnedApmWindows {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][version]$Version,
        [Parameter(Mandatory)][string]$ChecksumPath
    )

    $assetName = 'apm-windows-x86_64.zip'
    $memberName = 'apm-windows-x86_64/apm.exe'
    $layout = Get-ApmWindowsLayout -Version $Version
    Assert-ApmWindowsLayoutSafe -Layout $layout

    $tempDirectory = Join-Path ([System.IO.Path]::GetTempPath()) `
        ('apm-secure-install-{0}' -f [Guid]::NewGuid().ToString('N'))
    $archivePath = Join-Path $tempDirectory $assetName
    $extractDirectory = Join-Path $tempDirectory 'extract'
    $packageDirectory = Join-Path $extractDirectory 'apm-windows-x86_64'
    $stagingDirectory = "$($layout.ReleaseDirectory).new-$([Guid]::NewGuid().ToString('N'))"
    $oldReleaseDirectory = $null
    $newCurrentDirectory = "$($layout.CurrentDirectory).new-$([Guid]::NewGuid().ToString('N'))"
    $oldCurrentDirectory = $null
    $stagedShimPath = "$($layout.ShimPath).new-$([Guid]::NewGuid().ToString('N'))"
    $oldShimPath = $null
    $createdDirectories = @()
    $releasePromoted = $false
    $currentPromoted = $false
    $shimPromoted = $false
    $previousUserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $previousProcessPath = $env:PATH
    $pathUpdated = $false

    try {
        Assert-PathAncestorsWithoutReparsePoint -Path $tempDirectory `
            -Description 'Private APM staging directory'
        $null = New-Item -ItemType Directory -Path $tempDirectory
        $null = New-Item -ItemType Directory -Path $extractDirectory
        Assert-PathWithoutReparsePoint -Path $tempDirectory -PathType Directory -Recurse `
            -Description 'Private APM staging directory'

        $previousSecurityProtocol = [Net.ServicePointManager]::SecurityProtocol
        try {
            [Net.ServicePointManager]::SecurityProtocol = $previousSecurityProtocol -bor `
                [Net.SecurityProtocolType]::Tls12
            $downloadUrl = "https://github.com/microsoft/apm/releases/download/v$Version/$assetName"
            Invoke-WebRequest -Uri $downloadUrl -OutFile $archivePath -UseBasicParsing
        }
        finally {
            [Net.ServicePointManager]::SecurityProtocol = $previousSecurityProtocol
        }
        Assert-PinnedFileChecksum -Path $archivePath -ChecksumPath $ChecksumPath -FileName $assetName
        Expand-Archive -LiteralPath $archivePath -DestinationPath $extractDirectory -Force

        $topLevelItems = @(Get-ChildItem -LiteralPath $extractDirectory -Force)
        if ($topLevelItems.Count -ne 1 -or $topLevelItems[0].Name -cne 'apm-windows-x86_64' -or
            -not $topLevelItems[0].PSIsContainer) {
            throw 'Downloaded APM ZIP has an unexpected package layout.'
        }
        Assert-PathWithoutReparsePoint -Path $packageDirectory -PathType Directory -Recurse `
            -Description 'Downloaded APM bundle'
        $downloadedExecutable = Join-Path $packageDirectory 'apm.exe'
        Assert-PinnedFileChecksum -Path $downloadedExecutable -ChecksumPath $ChecksumPath `
            -FileName $memberName

        foreach ($directory in @(
                $layout.InstallRoot,
                $layout.BinDirectory,
                $layout.ReleasesDirectory
            )) {
            if (-not [System.IO.Directory]::Exists($directory)) {
                $null = New-Item -ItemType Directory -Path $directory
                $createdDirectories += $directory
            }
        }
        Assert-ApmWindowsLayoutSafe -Layout $layout
        Move-Item -LiteralPath $packageDirectory -Destination $stagingDirectory

        if ([System.IO.Directory]::Exists($layout.ReleaseDirectory)) {
            $oldReleaseDirectory = "$($layout.ReleaseDirectory).old-$([Guid]::NewGuid().ToString('N'))"
            Move-Item -LiteralPath $layout.ReleaseDirectory -Destination $oldReleaseDirectory
        }
        Move-Item -LiteralPath $stagingDirectory -Destination $layout.ReleaseDirectory
        $releasePromoted = $true

        $null = New-Item -ItemType Junction -Path $newCurrentDirectory `
            -Target $layout.ReleaseDirectory
        $currentItem = Get-Item -LiteralPath $layout.CurrentDirectory -Force -ErrorAction SilentlyContinue
        if ($null -ne $currentItem) {
            $oldCurrentDirectory = "$($layout.CurrentDirectory).old-$([Guid]::NewGuid().ToString('N'))"
            Move-Item -LiteralPath $layout.CurrentDirectory -Destination $oldCurrentDirectory
        }
        Move-Item -LiteralPath $newCurrentDirectory -Destination $layout.CurrentDirectory
        $currentPromoted = $true

        if ([System.IO.File]::Exists($layout.ShimPath)) {
            $oldShimPath = "$($layout.ShimPath).old-$([Guid]::NewGuid().ToString('N'))"
            Move-Item -LiteralPath $layout.ShimPath -Destination $oldShimPath
        }
        $shimContent = ConvertTo-ApmCommandShimContent
        Set-Content -LiteralPath $stagedShimPath -Value $shimContent -Encoding Ascii -NoNewline
        Move-Item -LiteralPath $stagedShimPath -Destination $layout.ShimPath
        $shimPromoted = $true

        Assert-PinnedFileChecksum -Path $layout.CurrentExecutable -ChecksumPath $ChecksumPath `
            -FileName $memberName
        $activeVersion = ConvertTo-ApmVersion -Text (
            (& $layout.CurrentExecutable --version 2>&1) -join "`n"
        )
        if ($LASTEXITCODE -ne 0) {
            throw "Promoted APM executable failed with exit code $LASTEXITCODE."
        }
        if ($activeVersion -ne $Version) {
            throw "APM installation completed but version $Version is not active."
        }

        $pathUpdated = $true
        Set-ApmUserPath -CurrentDirectory $layout.CurrentDirectory -BinDirectory $layout.BinDirectory `
            -Confirm:$false

        if ($null -ne $oldShimPath -and [System.IO.File]::Exists($oldShimPath)) {
            Remove-Item -LiteralPath $oldShimPath -Force -ErrorAction SilentlyContinue
        }
        if ($null -ne $oldCurrentDirectory) {
            try { Remove-ApmJunction -Path $oldCurrentDirectory -Confirm:$false }
            catch { Write-Verbose "Retained prior APM junction for manual cleanup: $oldCurrentDirectory" }
        }
        if ($null -ne $oldReleaseDirectory -and [System.IO.Directory]::Exists($oldReleaseDirectory)) {
            Remove-Item -LiteralPath $oldReleaseDirectory -Recurse -Force -ErrorAction SilentlyContinue
        }
        return $layout.CurrentExecutable
    }
    catch {
        $installationError = $_
        try {
            if ($pathUpdated) {
                [Environment]::SetEnvironmentVariable('Path', $previousUserPath, 'User')
                $env:PATH = $previousProcessPath
            }
            if ($shimPromoted -and [System.IO.File]::Exists($layout.ShimPath)) {
                Remove-Item -LiteralPath $layout.ShimPath -Force
            }
            if ($null -ne $oldShimPath -and [System.IO.File]::Exists($oldShimPath)) {
                Move-Item -LiteralPath $oldShimPath -Destination $layout.ShimPath
            }
            if ($currentPromoted) {
                Remove-ApmJunction -Path $layout.CurrentDirectory -Confirm:$false
            }
            if ($null -ne (Get-Item -LiteralPath $newCurrentDirectory -Force -ErrorAction SilentlyContinue)) {
                Remove-ApmJunction -Path $newCurrentDirectory -Confirm:$false
            }
            if ($null -ne $oldCurrentDirectory -and
                $null -ne (Get-Item -LiteralPath $oldCurrentDirectory -Force -ErrorAction SilentlyContinue)) {
                Move-Item -LiteralPath $oldCurrentDirectory -Destination $layout.CurrentDirectory
            }
            if ($releasePromoted -and [System.IO.Directory]::Exists($layout.ReleaseDirectory)) {
                Remove-Item -LiteralPath $layout.ReleaseDirectory -Recurse -Force
            }
            if ($null -ne $oldReleaseDirectory -and [System.IO.Directory]::Exists($oldReleaseDirectory)) {
                Move-Item -LiteralPath $oldReleaseDirectory -Destination $layout.ReleaseDirectory
            }
            foreach ($path in @($stagedShimPath, $stagingDirectory)) {
                if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Recurse -Force }
            }
            for ($index = $createdDirectories.Count - 1; $index -ge 0; $index--) {
                if ([System.IO.Directory]::Exists($createdDirectories[$index])) {
                    [System.IO.Directory]::Delete($createdDirectories[$index], $false)
                }
            }
        }
        catch {
            throw "APM CLI installation failed and its prior layout could not be fully restored: $installationError; rollback: $_"
        }
        throw $installationError
    }
    finally {
        if ([System.IO.Directory]::Exists($tempDirectory)) {
            Remove-Item -LiteralPath $tempDirectory -Recurse -Force
        }
    }
}

function Invoke-PinnedApmCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Executable,
        [Parameter(Mandatory)][string]$ChecksumPath,
        [Parameter(Mandatory)][string[]]$ArgumentList,
        [Parameter()][string]$WorkingDirectory
    )

    Assert-PinnedFileChecksum -Path $Executable -ChecksumPath $ChecksumPath `
        -FileName 'apm-windows-x86_64/apm.exe'
    Invoke-ExternalCommand -Executable $Executable -ArgumentList $ArgumentList `
        -WorkingDirectory $WorkingDirectory
}

function Invoke-ExternalCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Executable,

        [Parameter(Mandatory)]
        [string[]]$ArgumentList,

        [Parameter()]
        [string]$WorkingDirectory
    )

    $pushed = $false
    try {
        if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) {
            Push-Location -LiteralPath $WorkingDirectory
            $pushed = $true
        }
        & $Executable @ArgumentList
        if ($LASTEXITCODE -ne 0) {
            $renderedArguments = $ArgumentList -join ' '
            throw "Native command failed with exit code ${LASTEXITCODE}: $Executable $renderedArguments"
        }
    }
    finally {
        if ($pushed) {
            Pop-Location
        }
    }
}

function Copy-ManagedPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Source,

        [Parameter(Mandatory)]
        [string]$Destination
    )

    $parentPath = Split-Path -Parent $Destination
    if (-not (Test-Path -LiteralPath $parentPath -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $parentPath -Force
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
}

function Remove-ManagedPath {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if ((Test-Path -LiteralPath $Path) -and $PSCmdlet.ShouldProcess($Path, 'Remove managed path')) {
        Remove-Item -LiteralPath $Path -Recurse -Force
    }
}

function Set-ManagedPath {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter(Mandatory)]
        [string]$Source,

        [Parameter(Mandatory)]
        [string]$Destination
    )

    if ($PSCmdlet.ShouldProcess($Destination, 'Replace managed path')) {
        $stagedPath = '{0}.agent-baseline-stage-{1}' -f $Destination, [Guid]::NewGuid().ToString('N')
        Copy-ManagedPath -Source $Source -Destination $stagedPath
        try {
            Remove-ManagedPath -Path $Destination -Confirm:$false
            Move-Item -LiteralPath $stagedPath -Destination $Destination
        }
        finally {
            if (Test-Path -LiteralPath $stagedPath) {
                Remove-ManagedPath -Path $stagedPath -Confirm:$false
            }
        }
    }
}

function Get-DirectoryInventory {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    $root = [System.IO.Path]::GetFullPath($Path).TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar
    )
    $items = @(Get-ChildItem -LiteralPath $root -Force -Recurse | Sort-Object -Property FullName)
    foreach ($item in $items) {
        $relativePath = $item.FullName.Substring($root.Length).TrimStart(
            [System.IO.Path]::DirectorySeparatorChar,
            [System.IO.Path]::AltDirectorySeparatorChar
        )
        if ($item.PSIsContainer) {
            Write-Output "D`t$relativePath"
        }
        else {
            $hash = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash
            Write-Output "F`t$relativePath`t$hash"
        }
    }
}

function Test-DirectoryContentEqual {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ReferencePath,

        [Parameter(Mandatory)]
        [string]$DifferencePath
    )

    if (-not (Test-Path -LiteralPath $ReferencePath -PathType Container) -or
        -not (Test-Path -LiteralPath $DifferencePath -PathType Container)) {
        return $false
    }

    $reference = @(Get-DirectoryInventory -Path $ReferencePath)
    $difference = @(Get-DirectoryInventory -Path $DifferencePath)
    return (($reference -join "`n") -ceq ($difference -join "`n"))
}

function Test-LockfileContentEqual {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ReferencePath,

        [Parameter(Mandatory)]
        [string]$DifferencePath
    )

    if (-not [System.IO.File]::Exists($ReferencePath) -or
        -not [System.IO.File]::Exists($DifferencePath)) {
        return $false
    }

    $reference = @([System.IO.File]::ReadAllLines($ReferencePath) | Where-Object { $_ -notmatch '^generated_at:' })
    $difference = @([System.IO.File]::ReadAllLines($DifferencePath) | Where-Object { $_ -notmatch '^generated_at:' })
    return (($reference -join "`n") -ceq ($difference -join "`n"))
}

function Save-GlobalSnapshotPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$RelativePath,

        [Parameter(Mandatory)]
        [string]$SnapshotRoot,

        [Parameter(Mandatory)]
        [string]$InventoryPath,

        [Parameter(Mandatory)]
        [string]$AbsentPath
    )

    $sourcePath = Join-Path -Path $HomePath -ChildPath $RelativePath
    if (Test-Path -LiteralPath $sourcePath) {
        Add-Content -LiteralPath $InventoryPath -Value "present`t$RelativePath" -Encoding UTF8
        Copy-ManagedPath -Source $sourcePath -Destination (Join-Path $SnapshotRoot $RelativePath)
    }
    else {
        Add-Content -LiteralPath $InventoryPath -Value "absent`t$RelativePath" -Encoding UTF8
        Add-Content -LiteralPath $AbsentPath -Value $RelativePath -Encoding UTF8
    }
}

function Restore-GlobalSnapshot {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$SnapshotRoot,

        [Parameter(Mandatory)]
        [string]$InventoryPath
    )

    foreach ($line in [System.IO.File]::ReadAllLines($InventoryPath)) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }
        $fields = $line -split "`t", 2
        $status = $fields[0].TrimStart([char]0xFEFF)
        $relativePath = $fields[1]
        $destinationPath = Join-Path -Path $HomePath -ChildPath $relativePath
        Remove-ManagedPath -Path $destinationPath -Confirm:$false
        if ($status -ceq 'present') {
            Copy-ManagedPath -Source (Join-Path $SnapshotRoot $relativePath) -Destination $destinationPath
        }
    }
}

function Get-ExplicitConfirmParameter {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Collections.IDictionary]$BoundParameters
    )

    $result = @{}
    if ($BoundParameters.Contains('Confirm')) {
        $result['Confirm'] = [bool]$BoundParameters['Confirm']
    }
    return $result
}

function Invoke-GlobalBootstrap {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory)]
        [string]$HomePath,

        [Parameter(Mandatory)]
        [string]$RepositoryRoot
    )

    $manifestPath = Join-Path -Path $RepositoryRoot -ChildPath 'apm.yml'
    $lockfilePath = Join-Path -Path $RepositoryRoot -ChildPath 'apm.lock.yaml'
    $sourceApmPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm'
    $versionPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm-version'
    $checksumPath = Join-Path -Path $RepositoryRoot -ChildPath '.apm-checksums'
    Assert-PathWithoutReparsePoint -Path $HomePath -PathType Directory -Description 'HOME'
    Assert-PathWithoutReparsePoint -Path $manifestPath -PathType File -Description 'Repository APM manifest'
    Assert-PathWithoutReparsePoint -Path $lockfilePath -PathType File -Description 'Repository APM lockfile'
    Assert-PathWithoutReparsePoint -Path $versionPath -PathType File -Description 'Repository APM version pin'
    Assert-PathWithoutReparsePoint -Path $checksumPath -PathType File `
        -Description 'Repository APM checksums'
    Assert-PathWithoutReparsePoint -Path $sourceApmPath -PathType Directory -Recurse `
        -Description 'Repository local APM source'
    foreach ($skillName in $script:LocalSkills) {
        $skillSource = Join-Path -Path $sourceApmPath -ChildPath "skills/$skillName"
        Assert-PathWithoutReparsePoint -Path $skillSource -PathType Directory -Recurse `
            -Description "Local skill source '$skillName'"
        Assert-PathWithoutReparsePoint -Path (Join-Path $skillSource 'SKILL.md') -PathType File `
            -Description "Local skill entrypoint '$skillName'"
    }

    $pinText = ([System.IO.File]::ReadAllLines($versionPath)[0]).Trim()
    if ($pinText -notmatch '^\d+\.\d+\.\d+$') {
        throw "The APM version pin is not a plain X.Y.Z version: $pinText"
    }
    $approvedVersion = [version]$pinText
    $apmCommand = @(Get-Command -Name apm -CommandType Application -ErrorAction SilentlyContinue)[0]
    $installedVersion = $null
    $apmExecutable = $null
    $apmAction = 'Install'
    if ($null -ne $apmCommand) {
        $layout = Get-ApmWindowsLayout -Version $approvedVersion
        $commandPath = [System.IO.Path]::GetFullPath($apmCommand.Source)
        $shimPath = [System.IO.Path]::GetFullPath($layout.ShimPath)
        $apmExecutable = if ($commandPath.Equals($shimPath, [StringComparison]::OrdinalIgnoreCase)) {
            if (-not [System.IO.File]::Exists($layout.CurrentExecutable)) {
                throw "Installed APM shim has no current executable: $commandPath"
            }
            $layout.CurrentExecutable
        }
        else {
            $commandPath
        }
        Assert-PinnedFileChecksum -Path $apmExecutable -ChecksumPath $checksumPath `
            -FileName 'apm-windows-x86_64/apm.exe'
        $versionText = (& $apmExecutable --version 2>&1) -join "`n"
        if ($LASTEXITCODE -ne 0) {
            throw "Installed APM executable failed with exit code $LASTEXITCODE."
        }
        $installedVersion = ConvertTo-ApmVersion -Text $versionText
        if ($installedVersion -ne $approvedVersion) {
            throw "Installed APM executable matches the reviewed digest but reports version $installedVersion; expected $approvedVersion."
        }
        $apmAction = 'None'
    }

    $globalApmDirectory = Join-Path -Path $HomePath -ChildPath '.apm'
    $codexDirectory = Join-Path -Path $HomePath -ChildPath '.codex'
    $copilotDirectory = Join-Path -Path $HomePath -ChildPath '.copilot'
    $agentsDirectory = Join-Path -Path $HomePath -ChildPath '.agents'
    $backupBase = Join-Path -Path $globalApmDirectory -ChildPath "backups/$($script:BackupNamespace)"
    $managedTargets = @(
        @{ Path = $globalApmDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $codexDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $copilotDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = $agentsDirectory; Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $agentsDirectory 'skills'); Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'backups'); Type = 'Directory'; Recurse = $false }
        @{ Path = $backupBase; Type = 'Directory'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'apm.yml'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory 'apm.lock.yaml'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $globalApmDirectory '.apm'); Type = 'Directory'; Recurse = $true }
        @{ Path = (Join-Path $globalApmDirectory 'apm_modules'); Type = 'Directory'; Recurse = $true }
        @{ Path = (Join-Path $globalApmDirectory 'config.json'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $codexDirectory 'AGENTS.md'); Type = 'File'; Recurse = $false }
        @{ Path = (Join-Path $copilotDirectory 'copilot-instructions.md'); Type = 'File'; Recurse = $false }
    )
    foreach ($skillName in $script:ManagedSkills) {
        $managedTargets += @{
            Path = (Join-Path $agentsDirectory "skills/$skillName")
            Type = 'Directory'
            Recurse = $true
        }
    }
    foreach ($target in $managedTargets) {
        Assert-PathWithoutReparsePoint -Path $target.Path -PathType $target.Type -AllowMissing `
            -Recurse:$target.Recurse `
            -Description 'Managed target'
    }

    $preflightDirectory = Join-Path -Path ([System.IO.Path]::GetTempPath()) `
        -ChildPath ('agent-baseline-preflight-{0}' -f [Guid]::NewGuid().ToString('N'))
    $null = [System.IO.Directory]::CreateDirectory($preflightDirectory)
    try {
        if (-not $PSCmdlet.ShouldProcess($HomePath, 'Deploy the reviewed global APM baseline')) {
            Write-Information -MessageData (
                "Dry run: APM CLI action: $apmAction (pinned version $approvedVersion)."
            ) -InformationAction Continue
            Write-Information -MessageData 'Preflight checks passed; no user-profile files were changed.' `
                -InformationAction Continue
            return
        }

        if ($apmAction -ne 'None') {
            $apmExecutable = Install-PinnedApmWindows -Version $approvedVersion `
                -ChecksumPath $checksumPath
        }
        else {
            if ([string]::IsNullOrWhiteSpace($apmExecutable)) {
                throw 'Required command is not available on PATH: apm'
            }
            Assert-PinnedFileChecksum -Path $apmExecutable -ChecksumPath $checksumPath `
                -FileName 'apm-windows-x86_64/apm.exe'
        }

        $null = New-Item -ItemType Directory -Path $backupBase -Force
        Assert-PathWithoutReparsePoint -Path $backupBase -PathType Directory `
            -Description 'Backup namespace'
        $timestamp = [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')
        $backupDirectory = Join-Path -Path $backupBase -ChildPath $timestamp
        $counter = 0
        while (Test-Path -LiteralPath $backupDirectory) {
            $counter++
            $backupDirectory = Join-Path -Path $backupBase -ChildPath "${timestamp}-$counter"
        }
        $snapshotRoot = Join-Path $backupDirectory 'snapshot'
        $inventoryPath = Join-Path $backupDirectory 'inventory.tsv'
        $absentPath = Join-Path $backupDirectory 'originally-absent.txt'
        $stagingRoot = Join-Path $backupDirectory 'staging'
        $null = New-Item -ItemType Directory -Path $snapshotRoot -Force
        $null = New-Item -ItemType Directory -Path $stagingRoot -Force
        Set-Content -LiteralPath $inventoryPath -Value @() -Encoding UTF8
        Set-Content -LiteralPath $absentPath -Value @() -Encoding UTF8

        $relativePaths = @(
            '.apm/apm.yml'
            '.apm/apm.lock.yaml'
            '.apm/.apm'
            '.apm/apm_modules'
            '.apm/config.json'
            '.codex/AGENTS.md'
            '.copilot/copilot-instructions.md'
        )
        foreach ($skillName in $script:ManagedSkills) {
            $relativePaths += ".agents/skills/$skillName"
        }
        foreach ($relativePath in $relativePaths) {
            Save-GlobalSnapshotPath -HomePath $HomePath -RelativePath $relativePath `
                -SnapshotRoot $snapshotRoot -InventoryPath $inventoryPath -AbsentPath $absentPath
        }

        Copy-ManagedPath -Source $manifestPath -Destination (Join-Path $stagingRoot 'apm.yml')
        Copy-ManagedPath -Source $lockfilePath -Destination (Join-Path $stagingRoot 'apm.lock.yaml')
        Copy-ManagedPath -Source $sourceApmPath -Destination (Join-Path $stagingRoot '.apm')
        if ((Get-FileHash -LiteralPath $manifestPath).Hash -cne
            (Get-FileHash -LiteralPath (Join-Path $stagingRoot 'apm.yml')).Hash) {
            throw 'Staged APM manifest verification failed.'
        }
        if ((Get-FileHash -LiteralPath $lockfilePath).Hash -cne
            (Get-FileHash -LiteralPath (Join-Path $stagingRoot 'apm.lock.yaml')).Hash) {
            throw 'Staged APM lockfile verification failed.'
        }
        if (-not (Test-DirectoryContentEqual -ReferencePath $sourceApmPath `
                -DifferencePath (Join-Path $stagingRoot '.apm'))) {
            throw 'Staged local APM source verification failed.'
        }

        $mutationStarted = $false
        try {
            $mutationStarted = $true
            Set-ManagedPath -Source (Join-Path $stagingRoot 'apm.yml') `
                -Destination (Join-Path $globalApmDirectory 'apm.yml') -Confirm:$false
            Set-ManagedPath -Source (Join-Path $stagingRoot 'apm.lock.yaml') `
                -Destination (Join-Path $globalApmDirectory 'apm.lock.yaml') -Confirm:$false
            Set-ManagedPath -Source (Join-Path $stagingRoot '.apm') `
                -Destination (Join-Path $globalApmDirectory '.apm') -Confirm:$false

            Remove-ManagedPath -Path (Join-Path $codexDirectory 'AGENTS.md') -Confirm:$false
            Remove-ManagedPath -Path (Join-Path $copilotDirectory 'copilot-instructions.md') -Confirm:$false
            foreach ($skillName in $script:ManagedSkills) {
                Remove-ManagedPath -Path (Join-Path $agentsDirectory "skills/$skillName") -Confirm:$false
            }

            Invoke-PinnedApmCommand -Executable $apmExecutable -ChecksumPath $checksumPath `
                -ArgumentList @('install', '--global', '--frozen')

            foreach ($skillName in $script:LocalSkills) {
                Set-ManagedPath -Source (Join-Path $globalApmDirectory ".apm/skills/$skillName") `
                    -Destination (Join-Path $agentsDirectory "skills/$skillName") -Confirm:$false
            }

            Invoke-PinnedApmCommand -Executable $apmExecutable -ChecksumPath $checksumPath `
                -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'codex', '--single-agents',
                    '--output', (Join-Path $codexDirectory 'AGENTS.md'), '--dry-run'
                )
            Invoke-PinnedApmCommand -Executable $apmExecutable -ChecksumPath $checksumPath `
                -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'copilot', '--single-agents',
                    '--output', (Join-Path $copilotDirectory 'copilot-instructions.md'), '--dry-run'
                )
            Invoke-PinnedApmCommand -Executable $apmExecutable -ChecksumPath $checksumPath `
                -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'codex', '--single-agents',
                    '--output', (Join-Path $codexDirectory 'AGENTS.md')
                )
            Invoke-PinnedApmCommand -Executable $apmExecutable -ChecksumPath $checksumPath `
                -WorkingDirectory $globalApmDirectory `
                -ArgumentList @(
                    'compile', '--target', 'copilot', '--single-agents',
                    '--output', (Join-Path $copilotDirectory 'copilot-instructions.md')
                )

            if ((Get-FileHash -LiteralPath $manifestPath).Hash -cne
                (Get-FileHash -LiteralPath (Join-Path $globalApmDirectory 'apm.yml')).Hash) {
                throw 'Deployed APM manifest differs from the reviewed source.'
            }
            if (-not (Test-LockfileContentEqual -ReferencePath $lockfilePath `
                    -DifferencePath (Join-Path $globalApmDirectory 'apm.lock.yaml'))) {
                throw 'Deployed APM lockfile differs from the reviewed source.'
            }
            if (-not (Test-DirectoryContentEqual -ReferencePath $sourceApmPath `
                    -DifferencePath (Join-Path $globalApmDirectory '.apm'))) {
                throw 'Deployed local APM sources differ from the reviewed source.'
            }
            foreach ($skillName in $script:LocalSkills) {
                if (-not (Test-DirectoryContentEqual `
                        -ReferencePath (Join-Path $sourceApmPath "skills/$skillName") `
                        -DifferencePath (Join-Path $agentsDirectory "skills/$skillName"))) {
                    throw "Deployed local skill differs from its reviewed source: $skillName"
                }
            }
            foreach ($skillName in $script:ManagedSkills) {
                if (-not (Test-Path -LiteralPath (Join-Path $agentsDirectory "skills/$skillName") `
                        -PathType Container)) {
                    throw "Managed skill was not deployed: $skillName"
                }
            }
            if (-not (Test-ApmGeneratedFile -Path (Join-Path $codexDirectory 'AGENTS.md'))) {
                throw 'Codex instructions do not contain the expected APM marker.'
            }
            if (-not (Test-ApmGeneratedFile -Path (Join-Path $copilotDirectory 'copilot-instructions.md'))) {
                throw 'Copilot instructions do not contain the expected APM marker.'
            }
            $mutationStarted = $false
            Write-Information -MessageData 'Global APM configuration is ready.' -InformationAction Continue
            Write-Information -MessageData "Rollback snapshot retained at: $backupDirectory" `
                -InformationAction Continue
            Write-Information -MessageData 'Start new Codex and Copilot sessions to load the configuration.' `
                -InformationAction Continue
        }
        catch {
            $deploymentError = $_
            if ($mutationStarted) {
                Write-Warning "Deployment failed; restoring snapshot: $backupDirectory"
                try {
                    Restore-GlobalSnapshot -HomePath $HomePath -SnapshotRoot $snapshotRoot `
                        -InventoryPath $inventoryPath
                    Write-Warning "Rollback completed successfully. Snapshot retained at: $backupDirectory"
                }
                catch {
                    Write-Warning "Rollback encountered errors. Preserve and inspect: $backupDirectory"
                    Write-Warning $_.Exception.Message
                }
            }
            throw $deploymentError
        }
    }
    finally {
        if ([System.IO.Directory]::Exists($preflightDirectory)) {
            [System.IO.Directory]::Delete($preflightDirectory, $true)
        }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) {
        throw 'Bootstrap-Global.ps1 supports Windows; use bootstrap-global.sh on Linux.'
    }
    $repositoryRoot = Split-Path -Parent $PSScriptRoot
    $homePath = $HOME
    if ([string]::IsNullOrWhiteSpace($homePath)) {
        throw 'HOME must be set.'
    }

    $invokeParameters = @{
        HomePath = $homePath
        RepositoryRoot = $repositoryRoot
        WhatIf = [bool]$WhatIfPreference
    }
    $explicitConfirmParameter = Get-ExplicitConfirmParameter -BoundParameters $PSBoundParameters
    foreach ($key in $explicitConfirmParameter.Keys) {
        $invokeParameters[$key] = $explicitConfirmParameter[$key]
    }
    Invoke-GlobalBootstrap @invokeParameters
}
