[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [ValidateSet('apm')]
    [string]$Tool,

    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ToolArgument
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$homePath = $env:FAKE_HOME
if ([string]::IsNullOrWhiteSpace($homePath)) {
    throw 'FAKE_HOME must be set.'
}

Add-Content -LiteralPath (Join-Path $homePath '.fake-command.log') `
    -Value ("{0} {1}" -f $Tool, ($ToolArgument -join ' '))

if ($ToolArgument.Count -gt 0 -and $ToolArgument[0] -ceq '--version') {
    $version = if ([string]::IsNullOrWhiteSpace($env:FAKE_APM_VERSION)) {
        '0.28.0'
    }
    else {
        $env:FAKE_APM_VERSION
    }
    Write-Output "APM $version"
    exit 0
}

if ($ToolArgument.Count -gt 0 -and $ToolArgument[0] -ceq 'install') {
    if ($env:FAKE_APM_FAIL_STAGE -ceq 'install') {
        exit 41
    }

    foreach ($skillName in @('code-simplification', 'dependabot', 'git-commit', 'github-actions-hardening', 'msgraph')) {
        $skillPath = Join-Path $homePath ".agents/skills/$skillName"
        $null = New-Item -ItemType Directory -Path $skillPath -Force
        Set-Content -LiteralPath (Join-Path $skillPath 'SKILL.md') -Value "installed $skillName"
    }
    $modulePath = Join-Path $homePath '.apm/apm_modules/fake'
    $null = New-Item -ItemType Directory -Path $modulePath -Force
    Set-Content -LiteralPath (Join-Path $modulePath 'state') -Value 'installed'
    Set-Content -LiteralPath (Join-Path $homePath '.apm/config.json') -Value '{"installed":true}'
    exit 0
}

if ($ToolArgument.Count -gt 0 -and $ToolArgument[0] -ceq 'compile') {
    $target = $null
    $outputPath = $null
    $dryRun = $false
    for ($index = 1; $index -lt $ToolArgument.Count; $index++) {
        switch ($ToolArgument[$index]) {
            '--target' {
                $index++
                $target = $ToolArgument[$index]
            }
            '--output' {
                $index++
                $outputPath = $ToolArgument[$index]
            }
            '--dry-run' {
                $dryRun = $true
            }
        }
    }

    $stage = if ($dryRun) { "compile-dry-$target" } else { "compile-write-$target" }
    if ($env:FAKE_APM_FAIL_STAGE -ceq $stage) {
        exit 42
    }
    if (-not $dryRun) {
        $null = New-Item -ItemType Directory -Path (Split-Path -Parent $outputPath) -Force
        Set-Content -LiteralPath $outputPath -Value @(
            '# AGENTS.md'
            '<!-- Generated by APM CLI from .apm/ primitives -->'
            $target
        )
    }
    exit 0
}

exit 43
